
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:47 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::Cat;

use SAN::Cat::Type::cat-import;
use SAN::Cat::Type::catListRecords;
use SAN::Cat::Type::catRecordBody;
use SAN::Cat::Type::catRecordHeader_type;
use SAN::Cat::Type::catRecordHeader;
use SAN::Cat::Type::catRecord;
use SAN::Cat::Type::catheader;
use SAN::Cat::Type::contact;
use SAN::Cat::Type::filedesc;
use SAN::Cat::cat-import;

use SAN::Cat::Pastor::Meta;

1;
