
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:08 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::DL;

use SAN::DL::Type::haArchipedia;
use SAN::DL::Type::haCollezioneVirtuale;
use SAN::DL::Type::haComplesso;
use SAN::DL::Type::haConservatore;
use SAN::DL::Type::haFrancobollo;
use SAN::DL::Type::haLettera;
use SAN::DL::Type::haParte;
use SAN::DL::Type::haPercorsoTematico;
use SAN::DL::Type::haPergamena;
use SAN::DL::Type::haPortaleTematico;
use SAN::DL::Type::haProgettoDigitalizzazione;
use SAN::DL::Type::haRisorsaBibliografica;
use SAN::DL::Type::haSigillo;
use SAN::DL::Type::haSistemaAderente;
use SAN::DL::haArchipedia;
use SAN::DL::haCollezioneVirtuale;
use SAN::DL::haComplesso;
use SAN::DL::haConservatore;
use SAN::DL::haFrancobollo;
use SAN::DL::haLettera;
use SAN::DL::haParte;
use SAN::DL::haPercorsoTematico;
use SAN::DL::haPergamena;
use SAN::DL::haPortaleTematico;
use SAN::DL::haProgettoDigitalizzazione;
use SAN::DL::haRisorsaBibliografica;
use SAN::DL::haSigillo;
use SAN::DL::haSistemaAderente;

use SAN::DL::Pastor::Meta;

1;
