
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::EAC;

use SAN::EAC::ns002::Type::actuateType;
use SAN::EAC::ns002::Type::arcType;
use SAN::EAC::ns002::Type::arcroleType;
use SAN::EAC::Type::biogHist;
use SAN::EAC::Type::control;
use SAN::EAC::Type::cpfDescription;
use SAN::EAC::Type::cpfRelation_descriptiveNote;
use SAN::EAC::Type::cpfRelation;
use SAN::EAC::Type::dateSet_date_localType;
use SAN::EAC::Type::dateSet_date;
use SAN::EAC::Type::dateSet;
use SAN::EAC::Type::date_standardDate_item_0002;
use SAN::EAC::Type::date_standardDate_item_0003;
use SAN::EAC::Type::date_standardDate;
use SAN::EAC::Type::description;
use SAN::EAC::Type::descriptiveEntries;
use SAN::EAC::Type::descriptiveEntry_descriptiveNote;
use SAN::EAC::Type::descriptiveEntry;
use SAN::EAC::Type::eac-cpf;
use SAN::EAC::Type::entityType;
use SAN::EAC::Type::existDates;
use SAN::EAC::ns002::Type::extended;
use SAN::EAC::ns002::Type::fromType;
use SAN::EAC::ns002::Type::hrefType;
use SAN::EAC::Type::identity_localType;
use SAN::EAC::Type::identity;
use SAN::EAC::ns002::Type::labelType;
use SAN::EAC::ns003::Type::lang_item_0001;
use SAN::EAC::ns003::Type::lang;
use SAN::EAC::ns002::Type::locatorType;
use SAN::EAC::Type::maintenanceStatus;
use SAN::EAC::Type::nameEntryParallel_nameEntry;
use SAN::EAC::Type::nameEntryParallel;
use SAN::EAC::Type::nameEntry;
use SAN::EAC::Type::otherRecordId;
use SAN::EAC::Type::placeDate_descriptiveNote;
use SAN::EAC::Type::placeDates;
use SAN::EAC::Type::placeDate;
use SAN::EAC::Type::relations;
use SAN::EAC::Type::resourceRelation;
use SAN::EAC::ns002::Type::resourceType;
use SAN::EAC::ns002::Type::roleType;
use SAN::EAC::ns002::Type::showType;
use SAN::EAC::ns002::Type::simple;
use SAN::EAC::Type::sources;
use SAN::EAC::Type::source;
use SAN::EAC::ns003::Type::space;
use SAN::EAC::Type::stringNotEmpty;
use SAN::EAC::ns002::Type::titleAttrType;
use SAN::EAC::ns002::Type::titleEltType;
use SAN::EAC::ns002::Type::toType;
use SAN::EAC::ns002::Type::typeType;
use SAN::EAC::ns002::arc;
use SAN::EAC::biogHist;
use SAN::EAC::control;
use SAN::EAC::cpfDescription;
use SAN::EAC::cpfRelation;
use SAN::EAC::dateSet;
use SAN::EAC::description;
use SAN::EAC::descriptiveEntries;
use SAN::EAC::descriptiveEntry;
use SAN::EAC::eac-cpf;
use SAN::EAC::entityType;
use SAN::EAC::existDates;
use SAN::EAC::identity;
use SAN::EAC::ns002::locator;
use SAN::EAC::maintenanceStatus;
use SAN::EAC::nameEntryParallel;
use SAN::EAC::nameEntry;
use SAN::EAC::otherRecordId;
use SAN::EAC::placeDates;
use SAN::EAC::placeDate;
use SAN::EAC::relationEntry;
use SAN::EAC::relations;
use SAN::EAC::resourceRelation;
use SAN::EAC::ns002::resource;
use SAN::EAC::sources;
use SAN::EAC::source;
use SAN::EAC::ns002::title;

use SAN::EAC::Pastor::Meta;

1;
