
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:48 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::EAD;

use SAN::EAD::Type::abstract;
use SAN::EAD::Type::archdesc_processinfo;
use SAN::EAD::Type::archdesc;
use SAN::EAD::Type::datetype_datechar;
use SAN::EAD::Type::datetype_normal_item_0001;
use SAN::EAD::Type::datetype_normal_item_0002;
use SAN::EAD::Type::datetype_normal;
use SAN::EAD::Type::datetype;
use SAN::EAD::Type::did;
use SAN::EAD::Type::ead;
use SAN::EAD::Type::otherfindaid;
use SAN::EAD::Type::physdesc;
use SAN::EAD::Type::relatedmaterial;
use SAN::EAD::Type::repository;
use SAN::EAD::Type::stringNotEmpty;
use SAN::EAD::Type::unitid;
use SAN::EAD::Type::unittitle;
use SAN::EAD::abstract;
use SAN::EAD::archdesc;
use SAN::EAD::did;
use SAN::EAD::ead;
use SAN::EAD::otherfindaid;
use SAN::EAD::physdesc;
use SAN::EAD::relatedmaterial;
use SAN::EAD::repository;
use SAN::EAD::unitid;
use SAN::EAD::unittitle;

use SAN::EAD::Pastor::Meta;

1;
