
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:08 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::Ricerca;

use SAN::Ricerca::Type::archdesc;
use SAN::Ricerca::Type::did;
use SAN::Ricerca::Type::eadheader;
use SAN::Ricerca::Type::eadid;
use SAN::Ricerca::Type::ead;
use SAN::Ricerca::Type::editionstmt;
use SAN::Ricerca::Type::edition;
use SAN::Ricerca::Type::extptr;
use SAN::Ricerca::Type::filedesc;
use SAN::Ricerca::Type::note_type;
use SAN::Ricerca::Type::notestmt;
use SAN::Ricerca::Type::note;
use SAN::Ricerca::Type::publicationstmt;
use SAN::Ricerca::Type::stringNotEmpty;
use SAN::Ricerca::Type::titlestmt;
use SAN::Ricerca::archdesc;
use SAN::Ricerca::did;
use SAN::Ricerca::eadheader;
use SAN::Ricerca::eadid;
use SAN::Ricerca::ead;
use SAN::Ricerca::editionstmt;
use SAN::Ricerca::edition;
use SAN::Ricerca::extptr;
use SAN::Ricerca::filedesc;
use SAN::Ricerca::notestmt;
use SAN::Ricerca::note;
use SAN::Ricerca::publicationstmt;
use SAN::Ricerca::titlestmt;

use SAN::Ricerca::Pastor::Meta;

1;
