
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Thu Jul  9 15:48:25 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::SCONS;

use SAN::SCONS::Type::formeparallele_formaautorizzata;
use SAN::SCONS::Type::formeparallele;
use SAN::SCONS::Type::identifier;
use SAN::SCONS::Type::localizzazione;
use SAN::SCONS::Type::scons;
use SAN::SCONS::Type::sitoweb;
use SAN::SCONS::formaautorizzata;
use SAN::SCONS::formeparallele;
use SAN::SCONS::identifier;
use SAN::SCONS::localizzazione;
use SAN::SCONS::scons;
use SAN::SCONS::sitoweb;

use SAN::SCONS::Pastor::Meta;

1;
