
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:08 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::DL::Pastor::Meta;


our @ISA=qw(XML::Pastor::Meta);

SAN::DL::Pastor::Meta->Model( bless( {
         'attribute' => {},
         'attributeGroup' => {},
         'defaultNamespace' => bless( {
                                        'classPrefix' => undef,
                                        'id' => 0,
                                        'nsPrefix' => undef,
                                        'uri' => 'http://mibac.it/san/dl#',
                                        'usageCount' => 1
                                      }, 'XML::Pastor::Schema::NamespaceInfo' ),
         'element' => {
                        'haArchipedia|http://mibac.it/san/dl#' => bless( {
                                                                         'baseClasses' => [
                                                                                            'SAN::DL::Type::haArchipedia',
                                                                                            'XML::Pastor::Element'
                                                                                          ],
                                                                         'class' => 'SAN::DL::haArchipedia',
                                                                         'isRedefinable' => 1,
                                                                         'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                         'name' => 'haArchipedia',
                                                                         'scope' => 'global',
                                                                         'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                         'type' => 'haArchipedia|http://mibac.it/san/dl#'
                                                                       }, 'XML::Pastor::Schema::Element' ),
                        'haCollezioneVirtuale|http://mibac.it/san/dl#' => bless( {
                                                                                 'baseClasses' => [
                                                                                                    'SAN::DL::Type::haCollezioneVirtuale',
                                                                                                    'XML::Pastor::Element'
                                                                                                  ],
                                                                                 'class' => 'SAN::DL::haCollezioneVirtuale',
                                                                                 'isRedefinable' => 1,
                                                                                 'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                                 'name' => 'haCollezioneVirtuale',
                                                                                 'scope' => 'global',
                                                                                 'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                                 'type' => 'haCollezioneVirtuale|http://mibac.it/san/dl#'
                                                                               }, 'XML::Pastor::Schema::Element' ),
                        'haComplesso|http://mibac.it/san/dl#' => bless( {
                                                                        'baseClasses' => [
                                                                                           'SAN::DL::Type::haComplesso',
                                                                                           'XML::Pastor::Element'
                                                                                         ],
                                                                        'class' => 'SAN::DL::haComplesso',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                        'name' => 'haComplesso',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                        'type' => 'haComplesso|http://mibac.it/san/dl#'
                                                                      }, 'XML::Pastor::Schema::Element' ),
                        'haConservatore|http://mibac.it/san/dl#' => bless( {
                                                                           'baseClasses' => [
                                                                                              'SAN::DL::Type::haConservatore',
                                                                                              'XML::Pastor::Element'
                                                                                            ],
                                                                           'class' => 'SAN::DL::haConservatore',
                                                                           'isRedefinable' => 1,
                                                                           'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                           'name' => 'haConservatore',
                                                                           'scope' => 'global',
                                                                           'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                           'type' => 'haConservatore|http://mibac.it/san/dl#'
                                                                         }, 'XML::Pastor::Schema::Element' ),
                        'haFrancobollo|http://mibac.it/san/dl#' => bless( {
                                                                          'baseClasses' => [
                                                                                             'SAN::DL::Type::haFrancobollo',
                                                                                             'XML::Pastor::Element'
                                                                                           ],
                                                                          'class' => 'SAN::DL::haFrancobollo',
                                                                          'isRedefinable' => 1,
                                                                          'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                          'name' => 'haFrancobollo',
                                                                          'scope' => 'global',
                                                                          'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                          'type' => 'haFrancobollo|http://mibac.it/san/dl#'
                                                                        }, 'XML::Pastor::Schema::Element' ),
                        'haLettera|http://mibac.it/san/dl#' => bless( {
                                                                      'baseClasses' => [
                                                                                         'SAN::DL::Type::haLettera',
                                                                                         'XML::Pastor::Element'
                                                                                       ],
                                                                      'class' => 'SAN::DL::haLettera',
                                                                      'isRedefinable' => 1,
                                                                      'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                      'name' => 'haLettera',
                                                                      'scope' => 'global',
                                                                      'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                      'type' => 'haLettera|http://mibac.it/san/dl#'
                                                                    }, 'XML::Pastor::Schema::Element' ),
                        'haParte|http://mibac.it/san/dl#' => bless( {
                                                                    'baseClasses' => [
                                                                                       'SAN::DL::Type::haParte',
                                                                                       'XML::Pastor::Element'
                                                                                     ],
                                                                    'class' => 'SAN::DL::haParte',
                                                                    'isRedefinable' => 1,
                                                                    'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                    'name' => 'haParte',
                                                                    'scope' => 'global',
                                                                    'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                    'type' => 'haParte|http://mibac.it/san/dl#'
                                                                  }, 'XML::Pastor::Schema::Element' ),
                        'haPercorsoTematico|http://mibac.it/san/dl#' => bless( {
                                                                               'baseClasses' => [
                                                                                                  'SAN::DL::Type::haPercorsoTematico',
                                                                                                  'XML::Pastor::Element'
                                                                                                ],
                                                                               'class' => 'SAN::DL::haPercorsoTematico',
                                                                               'isRedefinable' => 1,
                                                                               'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                               'name' => 'haPercorsoTematico',
                                                                               'scope' => 'global',
                                                                               'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                               'type' => 'haPercorsoTematico|http://mibac.it/san/dl#'
                                                                             }, 'XML::Pastor::Schema::Element' ),
                        'haPergamena|http://mibac.it/san/dl#' => bless( {
                                                                        'baseClasses' => [
                                                                                           'SAN::DL::Type::haPergamena',
                                                                                           'XML::Pastor::Element'
                                                                                         ],
                                                                        'class' => 'SAN::DL::haPergamena',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                        'name' => 'haPergamena',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                        'type' => 'haPergamena|http://mibac.it/san/dl#'
                                                                      }, 'XML::Pastor::Schema::Element' ),
                        'haPortaleTematico|http://mibac.it/san/dl#' => bless( {
                                                                              'baseClasses' => [
                                                                                                 'SAN::DL::Type::haPortaleTematico',
                                                                                                 'XML::Pastor::Element'
                                                                                               ],
                                                                              'class' => 'SAN::DL::haPortaleTematico',
                                                                              'isRedefinable' => 1,
                                                                              'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                              'name' => 'haPortaleTematico',
                                                                              'scope' => 'global',
                                                                              'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                              'type' => 'haPortaleTematico|http://mibac.it/san/dl#'
                                                                            }, 'XML::Pastor::Schema::Element' ),
                        'haProgettoDigitalizzazione|http://mibac.it/san/dl#' => bless( {
                                                                                       'baseClasses' => [
                                                                                                          'SAN::DL::Type::haProgettoDigitalizzazione',
                                                                                                          'XML::Pastor::Element'
                                                                                                        ],
                                                                                       'class' => 'SAN::DL::haProgettoDigitalizzazione',
                                                                                       'isRedefinable' => 1,
                                                                                       'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                                       'name' => 'haProgettoDigitalizzazione',
                                                                                       'scope' => 'global',
                                                                                       'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                                       'type' => 'haProgettoDigitalizzazione|http://mibac.it/san/dl#'
                                                                                     }, 'XML::Pastor::Schema::Element' ),
                        'haRisorsaBibliografica|http://mibac.it/san/dl#' => bless( {
                                                                                   'baseClasses' => [
                                                                                                      'SAN::DL::Type::haRisorsaBibliografica',
                                                                                                      'XML::Pastor::Element'
                                                                                                    ],
                                                                                   'class' => 'SAN::DL::haRisorsaBibliografica',
                                                                                   'isRedefinable' => 1,
                                                                                   'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                                   'name' => 'haRisorsaBibliografica',
                                                                                   'scope' => 'global',
                                                                                   'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                                   'type' => 'haRisorsaBibliografica|http://mibac.it/san/dl#'
                                                                                 }, 'XML::Pastor::Schema::Element' ),
                        'haSigillo|http://mibac.it/san/dl#' => bless( {
                                                                      'baseClasses' => [
                                                                                         'SAN::DL::Type::haSigillo',
                                                                                         'XML::Pastor::Element'
                                                                                       ],
                                                                      'class' => 'SAN::DL::haSigillo',
                                                                      'isRedefinable' => 1,
                                                                      'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                      'name' => 'haSigillo',
                                                                      'scope' => 'global',
                                                                      'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                      'type' => 'haSigillo|http://mibac.it/san/dl#'
                                                                    }, 'XML::Pastor::Schema::Element' ),
                        'haSistemaAderente|http://mibac.it/san/dl#' => bless( {
                                                                              'baseClasses' => [
                                                                                                 'SAN::DL::Type::haSistemaAderente',
                                                                                                 'XML::Pastor::Element'
                                                                                               ],
                                                                              'class' => 'SAN::DL::haSistemaAderente',
                                                                              'isRedefinable' => 1,
                                                                              'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                              'name' => 'haSistemaAderente',
                                                                              'scope' => 'global',
                                                                              'targetNamespace' => 'http://mibac.it/san/dl#',
                                                                              'type' => 'haSistemaAderente|http://mibac.it/san/dl#'
                                                                            }, 'XML::Pastor::Schema::Element' )
                      },
         'group' => {},
         'namespaceCounter' => 1,
         'namespaces' => {
                           'http://mibac.it/san/dl#' => bless( {
                                                               'classPrefix' => undef,
                                                               'id' => 0,
                                                               'nsPrefix' => undef,
                                                               'uri' => 'http://mibac.it/san/dl#',
                                                               'usageCount' => 1
                                                             }, 'XML::Pastor::Schema::NamespaceInfo' )
                         },
         'type' => {
                     'haArchipedia|http://mibac.it/san/dl#' => bless( {
                                                                      'attributeInfo' => {},
                                                                      'attributePrefix' => '_',
                                                                      'attributes' => [],
                                                                      'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                      'baseClasses' => [
                                                                                         'SAN::DL::Type::rdfProperty'
                                                                                       ],
                                                                      'class' => 'SAN::DL::Type::haArchipedia',
                                                                      'contentType' => 'complex',
                                                                      'derivedBy' => 'extension',
                                                                      'elementInfo' => {},
                                                                      'elements' => [],
                                                                      'isRedefinable' => 1,
                                                                      'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                      'name' => 'haArchipedia',
                                                                      'nameIsAutoGenerated' => 1,
                                                                      'scope' => 'local',
                                                                      'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                    }, 'XML::Pastor::Schema::ComplexType' ),
                     'haCollezioneVirtuale|http://mibac.it/san/dl#' => bless( {
                                                                              'attributeInfo' => {},
                                                                              'attributePrefix' => '_',
                                                                              'attributes' => [],
                                                                              'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                              'baseClasses' => [
                                                                                                 'SAN::DL::Type::rdfProperty'
                                                                                               ],
                                                                              'class' => 'SAN::DL::Type::haCollezioneVirtuale',
                                                                              'contentType' => 'complex',
                                                                              'derivedBy' => 'extension',
                                                                              'elementInfo' => {},
                                                                              'elements' => [],
                                                                              'isRedefinable' => 1,
                                                                              'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                              'name' => 'haCollezioneVirtuale',
                                                                              'nameIsAutoGenerated' => 1,
                                                                              'scope' => 'local',
                                                                              'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                            }, 'XML::Pastor::Schema::ComplexType' ),
                     'haComplesso|http://mibac.it/san/dl#' => bless( {
                                                                     'attributeInfo' => {},
                                                                     'attributePrefix' => '_',
                                                                     'attributes' => [],
                                                                     'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                     'baseClasses' => [
                                                                                        'SAN::DL::Type::rdfProperty'
                                                                                      ],
                                                                     'class' => 'SAN::DL::Type::haComplesso',
                                                                     'contentType' => 'complex',
                                                                     'derivedBy' => 'extension',
                                                                     'elementInfo' => {},
                                                                     'elements' => [],
                                                                     'isRedefinable' => 1,
                                                                     'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                     'name' => 'haComplesso',
                                                                     'nameIsAutoGenerated' => 1,
                                                                     'scope' => 'local',
                                                                     'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                   }, 'XML::Pastor::Schema::ComplexType' ),
                     'haConservatore|http://mibac.it/san/dl#' => bless( {
                                                                        'attributeInfo' => {},
                                                                        'attributePrefix' => '_',
                                                                        'attributes' => [],
                                                                        'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                        'baseClasses' => [
                                                                                           'SAN::DL::Type::rdfProperty'
                                                                                         ],
                                                                        'class' => 'SAN::DL::Type::haConservatore',
                                                                        'contentType' => 'complex',
                                                                        'derivedBy' => 'extension',
                                                                        'elementInfo' => {},
                                                                        'elements' => [],
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                        'name' => 'haConservatore',
                                                                        'nameIsAutoGenerated' => 1,
                                                                        'scope' => 'local',
                                                                        'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                      }, 'XML::Pastor::Schema::ComplexType' ),
                     'haFrancobollo|http://mibac.it/san/dl#' => bless( {
                                                                       'attributeInfo' => {},
                                                                       'attributePrefix' => '_',
                                                                       'attributes' => [],
                                                                       'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                       'baseClasses' => [
                                                                                          'SAN::DL::Type::rdfProperty'
                                                                                        ],
                                                                       'class' => 'SAN::DL::Type::haFrancobollo',
                                                                       'contentType' => 'complex',
                                                                       'derivedBy' => 'extension',
                                                                       'elementInfo' => {},
                                                                       'elements' => [],
                                                                       'isRedefinable' => 1,
                                                                       'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                       'name' => 'haFrancobollo',
                                                                       'nameIsAutoGenerated' => 1,
                                                                       'scope' => 'local',
                                                                       'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                     }, 'XML::Pastor::Schema::ComplexType' ),
                     'haLettera|http://mibac.it/san/dl#' => bless( {
                                                                   'attributeInfo' => {},
                                                                   'attributePrefix' => '_',
                                                                   'attributes' => [],
                                                                   'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                   'baseClasses' => [
                                                                                      'SAN::DL::Type::rdfProperty'
                                                                                    ],
                                                                   'class' => 'SAN::DL::Type::haLettera',
                                                                   'contentType' => 'complex',
                                                                   'derivedBy' => 'extension',
                                                                   'elementInfo' => {},
                                                                   'elements' => [],
                                                                   'isRedefinable' => 1,
                                                                   'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                   'name' => 'haLettera',
                                                                   'nameIsAutoGenerated' => 1,
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                 }, 'XML::Pastor::Schema::ComplexType' ),
                     'haParte|http://mibac.it/san/dl#' => bless( {
                                                                 'attributeInfo' => {},
                                                                 'attributePrefix' => '_',
                                                                 'attributes' => [],
                                                                 'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                 'baseClasses' => [
                                                                                    'SAN::DL::Type::rdfProperty'
                                                                                  ],
                                                                 'class' => 'SAN::DL::Type::haParte',
                                                                 'contentType' => 'complex',
                                                                 'derivedBy' => 'extension',
                                                                 'elementInfo' => {},
                                                                 'elements' => [],
                                                                 'isRedefinable' => 1,
                                                                 'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                 'name' => 'haParte',
                                                                 'nameIsAutoGenerated' => 1,
                                                                 'scope' => 'local',
                                                                 'targetNamespace' => 'http://mibac.it/san/dl#'
                                                               }, 'XML::Pastor::Schema::ComplexType' ),
                     'haPercorsoTematico|http://mibac.it/san/dl#' => bless( {
                                                                            'attributeInfo' => {},
                                                                            'attributePrefix' => '_',
                                                                            'attributes' => [],
                                                                            'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                            'baseClasses' => [
                                                                                               'SAN::DL::Type::rdfProperty'
                                                                                             ],
                                                                            'class' => 'SAN::DL::Type::haPercorsoTematico',
                                                                            'contentType' => 'complex',
                                                                            'derivedBy' => 'extension',
                                                                            'elementInfo' => {},
                                                                            'elements' => [],
                                                                            'isRedefinable' => 1,
                                                                            'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                            'name' => 'haPercorsoTematico',
                                                                            'nameIsAutoGenerated' => 1,
                                                                            'scope' => 'local',
                                                                            'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                          }, 'XML::Pastor::Schema::ComplexType' ),
                     'haPergamena|http://mibac.it/san/dl#' => bless( {
                                                                     'attributeInfo' => {},
                                                                     'attributePrefix' => '_',
                                                                     'attributes' => [],
                                                                     'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                     'baseClasses' => [
                                                                                        'SAN::DL::Type::rdfProperty'
                                                                                      ],
                                                                     'class' => 'SAN::DL::Type::haPergamena',
                                                                     'contentType' => 'complex',
                                                                     'derivedBy' => 'extension',
                                                                     'elementInfo' => {},
                                                                     'elements' => [],
                                                                     'isRedefinable' => 1,
                                                                     'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                     'name' => 'haPergamena',
                                                                     'nameIsAutoGenerated' => 1,
                                                                     'scope' => 'local',
                                                                     'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                   }, 'XML::Pastor::Schema::ComplexType' ),
                     'haPortaleTematico|http://mibac.it/san/dl#' => bless( {
                                                                           'attributeInfo' => {},
                                                                           'attributePrefix' => '_',
                                                                           'attributes' => [],
                                                                           'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                           'baseClasses' => [
                                                                                              'SAN::DL::Type::rdfProperty'
                                                                                            ],
                                                                           'class' => 'SAN::DL::Type::haPortaleTematico',
                                                                           'contentType' => 'complex',
                                                                           'derivedBy' => 'extension',
                                                                           'elementInfo' => {},
                                                                           'elements' => [],
                                                                           'isRedefinable' => 1,
                                                                           'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                           'name' => 'haPortaleTematico',
                                                                           'nameIsAutoGenerated' => 1,
                                                                           'scope' => 'local',
                                                                           'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                         }, 'XML::Pastor::Schema::ComplexType' ),
                     'haProgettoDigitalizzazione|http://mibac.it/san/dl#' => bless( {
                                                                                    'attributeInfo' => {},
                                                                                    'attributePrefix' => '_',
                                                                                    'attributes' => [],
                                                                                    'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                                    'baseClasses' => [
                                                                                                       'SAN::DL::Type::rdfProperty'
                                                                                                     ],
                                                                                    'class' => 'SAN::DL::Type::haProgettoDigitalizzazione',
                                                                                    'contentType' => 'complex',
                                                                                    'derivedBy' => 'extension',
                                                                                    'elementInfo' => {},
                                                                                    'elements' => [],
                                                                                    'isRedefinable' => 1,
                                                                                    'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                                    'name' => 'haProgettoDigitalizzazione',
                                                                                    'nameIsAutoGenerated' => 1,
                                                                                    'scope' => 'local',
                                                                                    'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                                  }, 'XML::Pastor::Schema::ComplexType' ),
                     'haRisorsaBibliografica|http://mibac.it/san/dl#' => bless( {
                                                                                'attributeInfo' => {},
                                                                                'attributePrefix' => '_',
                                                                                'attributes' => [],
                                                                                'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                                'baseClasses' => [
                                                                                                   'SAN::DL::Type::rdfProperty'
                                                                                                 ],
                                                                                'class' => 'SAN::DL::Type::haRisorsaBibliografica',
                                                                                'contentType' => 'complex',
                                                                                'derivedBy' => 'extension',
                                                                                'elementInfo' => {},
                                                                                'elements' => [],
                                                                                'isRedefinable' => 1,
                                                                                'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                                'name' => 'haRisorsaBibliografica',
                                                                                'nameIsAutoGenerated' => 1,
                                                                                'scope' => 'local',
                                                                                'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                              }, 'XML::Pastor::Schema::ComplexType' ),
                     'haSigillo|http://mibac.it/san/dl#' => bless( {
                                                                   'attributeInfo' => {},
                                                                   'attributePrefix' => '_',
                                                                   'attributes' => [],
                                                                   'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                   'baseClasses' => [
                                                                                      'SAN::DL::Type::rdfProperty'
                                                                                    ],
                                                                   'class' => 'SAN::DL::Type::haSigillo',
                                                                   'contentType' => 'complex',
                                                                   'derivedBy' => 'extension',
                                                                   'elementInfo' => {},
                                                                   'elements' => [],
                                                                   'isRedefinable' => 1,
                                                                   'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                   'name' => 'haSigillo',
                                                                   'nameIsAutoGenerated' => 1,
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                 }, 'XML::Pastor::Schema::ComplexType' ),
                     'haSistemaAderente|http://mibac.it/san/dl#' => bless( {
                                                                           'attributeInfo' => {},
                                                                           'attributePrefix' => '_',
                                                                           'attributes' => [],
                                                                           'base' => 'rdfProperty|http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                                           'baseClasses' => [
                                                                                              'SAN::DL::Type::rdfProperty'
                                                                                            ],
                                                                           'class' => 'SAN::DL::Type::haSistemaAderente',
                                                                           'contentType' => 'complex',
                                                                           'derivedBy' => 'extension',
                                                                           'elementInfo' => {},
                                                                           'elements' => [],
                                                                           'isRedefinable' => 1,
                                                                           'metaClass' => 'SAN::DL::Pastor::Meta',
                                                                           'name' => 'haSistemaAderente',
                                                                           'nameIsAutoGenerated' => 1,
                                                                           'scope' => 'local',
                                                                           'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                         }, 'XML::Pastor::Schema::ComplexType' )
                   }
       }, 'XML::Pastor::Schema::Model' ) );

1;
