
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:09 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::METS::RDF::Type::RDF;

use SAN::METS::RDF::Type::RDF_Description;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::METS::RDF::Type::RDF->mk_accessors( qw(Description));

SAN::METS::RDF::Type::RDF->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::METS::RDF::Type::RDF',
         'contentType' => 'complex',
         'elementInfo' => {
                            'Description' => bless( {
                                                    'class' => 'SAN::METS::RDF::Type::RDF_Description',
                                                    'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                    'name' => 'Description',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                    'type' => 'RDF_Description|http://www.w3.org/1999/02/22-rdf-syntax-ns#'
                                                  }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'Description'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
         'name' => 'RDF',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::METS::RDF::Type::RDF>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:09 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<Description>()      - See L<SAN::METS::RDF::Type::RDF_Description>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
