
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:09 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::METS::RDF::Type::RDF_Description;


our @ISA=qw(XML::Pastor::ComplexType);

SAN::METS::RDF::Type::RDF_Description->mk_accessors( qw(_about haSistemaAderente haProgettoDigitalizzazione haConservatore haComplesso haSigillo haPergamena haLettera haFrancobollo haParte haCollezioneVirtuale haRisorsaBibliografica haPercorsoTematico haPortaleTematico haArchipedia));

# Attribute accessor aliases

sub about { &_about; }

SAN::METS::RDF::Type::RDF_Description->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'about' => bless( {
                                                'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                'form' => 'qualified',
                                                'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                'name' => 'about',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                                'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema',
                                                'use' => 'required'
                                              }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'about'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::METS::RDF::Type::RDF_Description',
         'contentType' => 'complex',
         'elementInfo' => {
                            'haArchipedia' => bless( {
                                                     'class' => undef,
                                                     'definition' => undef,
                                                     'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                     'minOccurs' => '0',
                                                     'name' => 'haArchipedia',
                                                     'nameIsAutoGenerated' => 1,
                                                     'ref' => 'haArchipedia|http://mibac.it/san/dl#',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://mibac.it/san/dl#'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'haCollezioneVirtuale' => bless( {
                                                             'class' => undef,
                                                             'definition' => undef,
                                                             'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                             'minOccurs' => '0',
                                                             'name' => 'haCollezioneVirtuale',
                                                             'nameIsAutoGenerated' => 1,
                                                             'ref' => 'haCollezioneVirtuale|http://mibac.it/san/dl#',
                                                             'scope' => 'local',
                                                             'targetNamespace' => 'http://mibac.it/san/dl#'
                                                           }, 'XML::Pastor::Schema::Element' ),
                            'haComplesso' => bless( {
                                                    'class' => undef,
                                                    'definition' => undef,
                                                    'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'haComplesso',
                                                    'nameIsAutoGenerated' => 1,
                                                    'ref' => 'haComplesso|http://mibac.it/san/dl#',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://mibac.it/san/dl#'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'haConservatore' => bless( {
                                                       'class' => undef,
                                                       'definition' => undef,
                                                       'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                       'minOccurs' => '0',
                                                       'name' => 'haConservatore',
                                                       'nameIsAutoGenerated' => 1,
                                                       'ref' => 'haConservatore|http://mibac.it/san/dl#',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://mibac.it/san/dl#'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'haFrancobollo' => bless( {
                                                      'class' => undef,
                                                      'definition' => undef,
                                                      'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'haFrancobollo',
                                                      'nameIsAutoGenerated' => 1,
                                                      'ref' => 'haFrancobollo|http://mibac.it/san/dl#',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://mibac.it/san/dl#'
                                                    }, 'XML::Pastor::Schema::Element' ),
                            'haLettera' => bless( {
                                                  'class' => undef,
                                                  'definition' => undef,
                                                  'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                  'minOccurs' => '0',
                                                  'name' => 'haLettera',
                                                  'nameIsAutoGenerated' => 1,
                                                  'ref' => 'haLettera|http://mibac.it/san/dl#',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://mibac.it/san/dl#'
                                                }, 'XML::Pastor::Schema::Element' ),
                            'haParte' => bless( {
                                                'class' => undef,
                                                'definition' => undef,
                                                'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                'minOccurs' => '0',
                                                'name' => 'haParte',
                                                'nameIsAutoGenerated' => 1,
                                                'ref' => 'haParte|http://mibac.it/san/dl#',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://mibac.it/san/dl#'
                                              }, 'XML::Pastor::Schema::Element' ),
                            'haPercorsoTematico' => bless( {
                                                           'class' => undef,
                                                           'definition' => undef,
                                                           'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'haPercorsoTematico',
                                                           'nameIsAutoGenerated' => 1,
                                                           'ref' => 'haPercorsoTematico|http://mibac.it/san/dl#',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://mibac.it/san/dl#'
                                                         }, 'XML::Pastor::Schema::Element' ),
                            'haPergamena' => bless( {
                                                    'class' => undef,
                                                    'definition' => undef,
                                                    'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'haPergamena',
                                                    'nameIsAutoGenerated' => 1,
                                                    'ref' => 'haPergamena|http://mibac.it/san/dl#',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://mibac.it/san/dl#'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'haPortaleTematico' => bless( {
                                                          'class' => undef,
                                                          'definition' => undef,
                                                          'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                          'minOccurs' => '0',
                                                          'name' => 'haPortaleTematico',
                                                          'nameIsAutoGenerated' => 1,
                                                          'ref' => 'haPortaleTematico|http://mibac.it/san/dl#',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://mibac.it/san/dl#'
                                                        }, 'XML::Pastor::Schema::Element' ),
                            'haProgettoDigitalizzazione' => bless( {
                                                                   'class' => undef,
                                                                   'definition' => undef,
                                                                   'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                                   'minOccurs' => '1',
                                                                   'name' => 'haProgettoDigitalizzazione',
                                                                   'nameIsAutoGenerated' => 1,
                                                                   'ref' => 'haProgettoDigitalizzazione|http://mibac.it/san/dl#',
                                                                   'scope' => 'local',
                                                                   'targetNamespace' => 'http://mibac.it/san/dl#'
                                                                 }, 'XML::Pastor::Schema::Element' ),
                            'haRisorsaBibliografica' => bless( {
                                                               'class' => undef,
                                                               'definition' => undef,
                                                               'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                               'minOccurs' => '0',
                                                               'name' => 'haRisorsaBibliografica',
                                                               'nameIsAutoGenerated' => 1,
                                                               'ref' => 'haRisorsaBibliografica|http://mibac.it/san/dl#',
                                                               'scope' => 'local',
                                                               'targetNamespace' => 'http://mibac.it/san/dl#'
                                                             }, 'XML::Pastor::Schema::Element' ),
                            'haSigillo' => bless( {
                                                  'class' => undef,
                                                  'definition' => undef,
                                                  'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                  'minOccurs' => '0',
                                                  'name' => 'haSigillo',
                                                  'nameIsAutoGenerated' => 1,
                                                  'ref' => 'haSigillo|http://mibac.it/san/dl#',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://mibac.it/san/dl#'
                                                }, 'XML::Pastor::Schema::Element' ),
                            'haSistemaAderente' => bless( {
                                                          'class' => undef,
                                                          'definition' => undef,
                                                          'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
                                                          'minOccurs' => '1',
                                                          'name' => 'haSistemaAderente',
                                                          'nameIsAutoGenerated' => 1,
                                                          'ref' => 'haSistemaAderente|http://mibac.it/san/dl#',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://mibac.it/san/dl#'
                                                        }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'haSistemaAderente',
                         'haProgettoDigitalizzazione',
                         'haConservatore',
                         'haComplesso',
                         'haSigillo',
                         'haPergamena',
                         'haLettera',
                         'haFrancobollo',
                         'haParte',
                         'haCollezioneVirtuale',
                         'haRisorsaBibliografica',
                         'haPercorsoTematico',
                         'haPortaleTematico',
                         'haArchipedia'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::METS::RDF::Pastor::Meta',
         'name' => 'RDF_Description',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::METS::RDF::Type::RDF_Description>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:09 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_about>(), B<about>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<haArchipedia>()

=item B<haCollezioneVirtuale>()

=item B<haComplesso>()

=item B<haConservatore>()

=item B<haFrancobollo>()

=item B<haLettera>()

=item B<haParte>()

=item B<haPercorsoTematico>()

=item B<haPergamena>()

=item B<haPortaleTematico>()

=item B<haProgettoDigitalizzazione>()

=item B<haRisorsaBibliografica>()

=item B<haSigillo>()

=item B<haSistemaAderente>()

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
