
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Thu Jul  9 15:48:25 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::SCONS::formaautorizzata;


our @ISA=qw(XML::Pastor::Builtin::string XML::Pastor::Element);

SAN::SCONS::formaautorizzata->XmlSchemaElement( bless( {
         'baseClasses' => [
                            'XML::Pastor::Builtin::string',
                            'XML::Pastor::Element'
                          ],
         'class' => 'SAN::SCONS::formaautorizzata',
         'isRedefinable' => 1,
         'metaClass' => 'SAN::SCONS::Pastor::Meta',
         'name' => 'formaautorizzata',
         'scope' => 'global',
         'targetNamespace' => 'http://san.mibac.it/scons-san/',
         'type' => 'string|http://www.w3.org/2001/XMLSchema'
       }, 'XML::Pastor::Schema::Element' ) );

1;


__END__



=head1 NAME

B<SAN::SCONS::formaautorizzata>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::string>, L<XML::Pastor::Element>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Thu Jul  9 15:48:25 2015'


=head1 SEE ALSO

L<XML::Pastor::Builtin::string>, L<XML::Pastor::Element>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
