
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Thu Jul  9 15:48:25 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::SCONS::localizzazione;

use SAN::SCONS::Type::localizzazione;

our @ISA=qw(SAN::SCONS::Type::localizzazione XML::Pastor::Element);

SAN::SCONS::localizzazione->XmlSchemaElement( bless( {
         'baseClasses' => [
                            'SAN::SCONS::Type::localizzazione',
                            'XML::Pastor::Element'
                          ],
         'class' => 'SAN::SCONS::localizzazione',
         'isRedefinable' => 1,
         'metaClass' => 'SAN::SCONS::Pastor::Meta',
         'name' => 'localizzazione',
         'scope' => 'global',
         'targetNamespace' => 'http://san.mibac.it/scons-san/',
         'type' => 'localizzazione|http://san.mibac.it/scons-san/'
       }, 'XML::Pastor::Schema::Element' ) );

1;


__END__



=head1 NAME

B<SAN::SCONS::localizzazione>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<SAN::SCONS::Type::localizzazione>, L<XML::Pastor::Element>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Thu Jul  9 15:48:25 2015'


=head1 SEE ALSO

L<SAN::SCONS::Type::localizzazione>, L<XML::Pastor::Element>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
