
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Thu Jul  9 15:48:25 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::SCONS::Type::localizzazione;


our @ISA=qw(XML::Pastor::Builtin::string);

SAN::SCONS::Type::localizzazione->mk_accessors( qw(_paese _provincia _comune _cap));

# Attribute accessor aliases

sub paese { &_paese; }
sub provincia { &_provincia; }
sub comune { &_comune; }
sub cap { &_cap; }

SAN::SCONS::Type::localizzazione->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'cap' => bless( {
                                              'class' => 'XML::Pastor::Builtin::nonNegativeInteger',
                                              'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                              'name' => 'cap',
                                              'scope' => 'local',
                                              'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                              'type' => 'nonNegativeInteger|http://www.w3.org/2001/XMLSchema',
                                              'use' => 'required'
                                            }, 'XML::Pastor::Schema::Attribute' ),
                              'comune' => bless( {
                                                 'class' => 'XML::Pastor::Builtin::string',
                                                 'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                 'name' => 'comune',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                 'type' => 'string|http://www.w3.org/2001/XMLSchema',
                                                 'use' => 'required'
                                               }, 'XML::Pastor::Schema::Attribute' ),
                              'paese' => bless( {
                                                'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                'name' => 'paese',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema',
                                                'use' => 'required'
                                              }, 'XML::Pastor::Schema::Attribute' ),
                              'provincia' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::string',
                                                    'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                    'name' => 'provincia',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                    'type' => 'string|http://www.w3.org/2001/XMLSchema',
                                                    'use' => 'required'
                                                  }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'paese',
                           'provincia',
                           'comune',
                           'cap'
                         ],
         'base' => 'string|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::string'
                          ],
         'class' => 'SAN::SCONS::Type::localizzazione',
         'contentType' => 'complex',
         'derivedBy' => 'extension',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'isSimpleContent' => 1,
         'metaClass' => 'SAN::SCONS::Pastor::Meta',
         'name' => 'localizzazione',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/scons-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::SCONS::Type::localizzazione>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::string>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Thu Jul  9 15:48:25 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_cap>(), B<cap>()      - See L<XML::Pastor::Builtin::nonNegativeInteger>.

=item B<_comune>(), B<comune>()      - See L<XML::Pastor::Builtin::string>.

=item B<_paese>(), B<paese>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=item B<_provincia>(), B<provincia>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::string>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
