
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Thu Jul  9 15:48:25 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::SCONS::Type::scons;

use SAN::SCONS::Type::formeparallele;
use SAN::SCONS::Type::identifier;
use SAN::SCONS::Type::localizzazione;
use SAN::SCONS::Type::sitoweb;
use SAN::SCONS::formaautorizzata;
use SAN::SCONS::formeparallele;
use SAN::SCONS::identifier;
use SAN::SCONS::localizzazione;
use SAN::SCONS::sitoweb;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::SCONS::Type::scons->mk_accessors( qw(formaautorizzata formeparallele acronimo identifier tipologia localizzazione sitoweb servizi descrizione orario altroaccesso consultazione altroaccesso consultazione));

SAN::SCONS::Type::scons->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::SCONS::Type::scons',
         'contentType' => 'complex',
         'elementInfo' => {
                            'acronimo' => bless( {
                                                 'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                 'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                 'minOccurs' => '0',
                                                 'name' => 'acronimo',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                 'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema'
                                               }, 'XML::Pastor::Schema::Element' ),
                            'altroaccesso' => bless( {
                                                     'class' => 'XML::Pastor::Builtin::string',
                                                     'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                     'name' => 'altroaccesso',
                                                     'scope' => 'local',
                                                     'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                     'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                   }, 'XML::Pastor::Schema::Element' ),
                            'consultazione' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::boolean',
                                                      'fixed' => 'false',
                                                      'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                      'name' => 'consultazione',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                      'type' => 'boolean|http://www.w3.org/2001/XMLSchema'
                                                    }, 'XML::Pastor::Schema::Element' ),
                            'descrizione' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::string',
                                                    'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'descrizione',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                    'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'formaautorizzata' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::string',
                                                         'definition' => bless( {
                                                                                  'baseClasses' => [
                                                                                                     'XML::Pastor::Builtin::string',
                                                                                                     'XML::Pastor::Element'
                                                                                                   ],
                                                                                  'class' => 'SAN::SCONS::formaautorizzata',
                                                                                  'isRedefinable' => 1,
                                                                                  'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                                                  'name' => 'formaautorizzata',
                                                                                  'scope' => 'global',
                                                                                  'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                                                  'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                }, 'XML::Pastor::Schema::Element' ),
                                                         'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                         'name' => 'formaautorizzata',
                                                         'nameIsAutoGenerated' => 1,
                                                         'ref' => 'formaautorizzata|http://san.mibac.it/scons-san/',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://san.mibac.it/scons-san/'
                                                       }, 'XML::Pastor::Schema::Element' ),
                            'formeparallele' => bless( {
                                                       'class' => 'SAN::SCONS::Type::formeparallele',
                                                       'definition' => bless( {
                                                                                'baseClasses' => [
                                                                                                   'SAN::SCONS::Type::formeparallele',
                                                                                                   'XML::Pastor::Element'
                                                                                                 ],
                                                                                'class' => 'SAN::SCONS::formeparallele',
                                                                                'isRedefinable' => 1,
                                                                                'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                                                'name' => 'formeparallele',
                                                                                'scope' => 'global',
                                                                                'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                                                'type' => 'formeparallele|http://san.mibac.it/scons-san/'
                                                                              }, 'XML::Pastor::Schema::Element' ),
                                                       'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                       'name' => 'formeparallele',
                                                       'nameIsAutoGenerated' => 1,
                                                       'ref' => 'formeparallele|http://san.mibac.it/scons-san/',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://san.mibac.it/scons-san/'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'identifier' => bless( {
                                                   'class' => 'SAN::SCONS::Type::identifier',
                                                   'definition' => bless( {
                                                                            'baseClasses' => [
                                                                                               'SAN::SCONS::Type::identifier',
                                                                                               'XML::Pastor::Element'
                                                                                             ],
                                                                            'class' => 'SAN::SCONS::identifier',
                                                                            'isRedefinable' => 1,
                                                                            'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                                            'name' => 'identifier',
                                                                            'scope' => 'global',
                                                                            'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                                            'type' => 'identifier|http://san.mibac.it/scons-san/'
                                                                          }, 'XML::Pastor::Schema::Element' ),
                                                   'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                   'name' => 'identifier',
                                                   'nameIsAutoGenerated' => 1,
                                                   'ref' => 'identifier|http://san.mibac.it/scons-san/',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://san.mibac.it/scons-san/'
                                                 }, 'XML::Pastor::Schema::Element' ),
                            'localizzazione' => bless( {
                                                       'class' => 'SAN::SCONS::Type::localizzazione',
                                                       'definition' => bless( {
                                                                                'baseClasses' => [
                                                                                                   'SAN::SCONS::Type::localizzazione',
                                                                                                   'XML::Pastor::Element'
                                                                                                 ],
                                                                                'class' => 'SAN::SCONS::localizzazione',
                                                                                'isRedefinable' => 1,
                                                                                'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                                                'name' => 'localizzazione',
                                                                                'scope' => 'global',
                                                                                'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                                                'type' => 'localizzazione|http://san.mibac.it/scons-san/'
                                                                              }, 'XML::Pastor::Schema::Element' ),
                                                       'maxOccurs' => 'unbounded',
                                                       'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                       'name' => 'localizzazione',
                                                       'nameIsAutoGenerated' => 1,
                                                       'ref' => 'localizzazione|http://san.mibac.it/scons-san/',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://san.mibac.it/scons-san/'
                                                     }, 'XML::Pastor::Schema::Element' ),
                            'orario' => bless( {
                                               'class' => 'XML::Pastor::Builtin::string',
                                               'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                               'name' => 'orario',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                               'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                             }, 'XML::Pastor::Schema::Element' ),
                            'servizi' => bless( {
                                                'class' => 'XML::Pastor::Builtin::string',
                                                'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                'minOccurs' => '0',
                                                'name' => 'servizi',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                              }, 'XML::Pastor::Schema::Element' ),
                            'sitoweb' => bless( {
                                                'class' => 'SAN::SCONS::Type::sitoweb',
                                                'definition' => bless( {
                                                                         'baseClasses' => [
                                                                                            'SAN::SCONS::Type::sitoweb',
                                                                                            'XML::Pastor::Element'
                                                                                          ],
                                                                         'class' => 'SAN::SCONS::sitoweb',
                                                                         'isRedefinable' => 1,
                                                                         'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                                         'name' => 'sitoweb',
                                                                         'scope' => 'global',
                                                                         'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                                         'type' => 'sitoweb|http://san.mibac.it/scons-san/'
                                                                       }, 'XML::Pastor::Schema::Element' ),
                                                'maxOccurs' => 'unbounded',
                                                'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                'minOccurs' => '0',
                                                'name' => 'sitoweb',
                                                'nameIsAutoGenerated' => 1,
                                                'ref' => 'sitoweb|http://san.mibac.it/scons-san/',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://san.mibac.it/scons-san/'
                                              }, 'XML::Pastor::Schema::Element' ),
                            'tipologia' => bless( {
                                                  'class' => 'XML::Pastor::Builtin::string',
                                                  'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                                  'name' => 'tipologia',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                                  'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'formaautorizzata',
                         'formeparallele',
                         'acronimo',
                         'identifier',
                         'tipologia',
                         'localizzazione',
                         'sitoweb',
                         'servizi',
                         'descrizione',
                         'orario',
                         'altroaccesso',
                         'consultazione',
                         'altroaccesso',
                         'consultazione'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::SCONS::Pastor::Meta',
         'name' => 'scons',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/scons-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::SCONS::Type::scons>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Thu Jul  9 15:48:25 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<acronimo>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=item B<altroaccesso>()      - See L<XML::Pastor::Builtin::string>.

=item B<altroaccesso>()      - See L<XML::Pastor::Builtin::string>.

=item B<consultazione>()      - See L<XML::Pastor::Builtin::boolean>.

=item B<consultazione>()      - See L<XML::Pastor::Builtin::boolean>.

=item B<descrizione>()      - See L<XML::Pastor::Builtin::string>.

=item B<formaautorizzata>()      - See L<XML::Pastor::Builtin::string>.

=item B<formeparallele>()      - See L<SAN::SCONS::Type::formeparallele>.

=item B<identifier>()      - See L<SAN::SCONS::Type::identifier>.

=item B<localizzazione>()      - See L<SAN::SCONS::Type::localizzazione>.

=item B<orario>()      - See L<XML::Pastor::Builtin::string>.

=item B<servizi>()      - See L<XML::Pastor::Builtin::string>.

=item B<sitoweb>()      - See L<SAN::SCONS::Type::sitoweb>.

=item B<tipologia>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
