
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Thu Jul  9 15:48:25 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::SCONS::Type::sitoweb;


our @ISA=qw(XML::Pastor::Builtin::string);

SAN::SCONS::Type::sitoweb->mk_accessors( qw(_href));

# Attribute accessor aliases

sub href { &_href; }

SAN::SCONS::Type::sitoweb->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'href' => bless( {
                                               'class' => 'XML::Pastor::Builtin::anyURI',
                                               'metaClass' => 'SAN::SCONS::Pastor::Meta',
                                               'name' => 'href',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://san.mibac.it/scons-san/',
                                               'type' => 'anyURI|http://www.w3.org/2001/XMLSchema',
                                               'use' => 'required'
                                             }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'href'
                         ],
         'base' => 'string|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::string'
                          ],
         'class' => 'SAN::SCONS::Type::sitoweb',
         'contentType' => 'complex',
         'derivedBy' => 'extension',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'isSimpleContent' => 1,
         'metaClass' => 'SAN::SCONS::Pastor::Meta',
         'name' => 'sitoweb',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/scons-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::SCONS::Type::sitoweb>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::string>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Thu Jul  9 15:48:25 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_href>(), B<href>()      - See L<XML::Pastor::Builtin::anyURI>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::string>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
