
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:09 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



package SAN::METS::RDF;

use SAN::METS::RDF::Type::RDF_Description;
use SAN::METS::RDF::Type::RDF;
use SAN::METS::RDF::Type::rdfProperty;
use SAN::METS::RDF::RDF;

use SAN::METS::RDF::Pastor::Meta;

1;
