
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:47 2015'
# ma alterato a mano fondendo gli altri Meta

# in data 30/06/2015 ho parzialmente ripristinato questo file allo stato attuale tranne che per recordBody ead
# 
#

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;

use SAN::EAD::Pastor::Meta;
package SAN::Cat::Pastor::Meta;

our @ISA=qw(XML::Pastor::Meta);

SAN::Cat::Pastor::Meta->Model( bless( {
         'attribute' => {},
         'attributeGroup' => {},
         'defaultNamespace' => bless( {
                                        'classPrefix' => undef,
                                        'id' => 0,
                                        'nsPrefix' => undef,
                                        'uri' => 'http://san.mibac.it/cat-import',
                                        'usageCount' => 1
                                      }, 'XML::Pastor::Schema::NamespaceInfo' ),
         'element' => {
                        'cat-import|http://san.mibac.it/cat-import' => bless( {
                                                                              'baseClasses' => [
                                                                                                 'SAN::Cat::Type::Import',
                                                                                                 'XML::Pastor::Element'
                                                                                               ],
                                                                              'class' => 'SAN::Cat::Import',
                                                                              'isRedefinable' => 1,
                                                                              'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                              'name' => 'cat-import',
                                                                              'scope' => 'global',
                                                                              'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                              'type' => 'cat-import|http://san.mibac.it/cat-import'
                                                                            }, 'XML::Pastor::Schema::Element' ),
                      },
         'group' => {},
         'namespaceCounter' => 1,
         'namespaces' => {
                           'http://san.mibac.it/cat-import' => bless( {
                                                                      'classPrefix' => undef,
                                                                      'id' => 0,
                                                                      'nsPrefix' => undef,
                                                                      'uri' => 'http://san.mibac.it/cat-import',
                                                                      'usageCount' => 1
                                                                    }, 'XML::Pastor::Schema::NamespaceInfo' ),
         },
         'type' => {
                     'cat-import|http://san.mibac.it/cat-import' => bless( {
                                                                           'attributeInfo' => {},
                                                                           'attributePrefix' => '_',
                                                                           'attributes' => [],
                                                                           'baseClasses' => [
                                                                                              'XML::Pastor::ComplexType'
                                                                                            ],
                                                                           'class' => 'SAN::Cat::Type::Import',
                                                                           'contentType' => 'complex',
                                                                           'elementInfo' => {
                                                                                              'catListRecords' => bless( {
                                                                                                                         'class' => 'SAN::Cat::Type::catListRecords',
                                                                                                                         'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                         'name' => 'catListRecords',
                                                                                                                         'scope' => 'local',
                                                                                                                         'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                         'type' => 'catListRecords|http://san.mibac.it/cat-import'
                                                                                                                       }, 'XML::Pastor::Schema::Element' ),
                                                                                              'catheader' => bless( {
                                                                                                                    'class' => 'SAN::Cat::Type::catheader',
                                                                                                                    'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                    'name' => 'catheader',
                                                                                                                    'scope' => 'local',
                                                                                                                    'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                    'type' => 'catheader|http://san.mibac.it/cat-import'
                                                                                                                  }, 'XML::Pastor::Schema::Element' )
                                                                                            },
                                                                           'elements' => [
                                                                                           'catheader',
                                                                                           'catListRecords'
                                                                                         ],
                                                                           'isRedefinable' => 1,
                                                                           'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                           'name' => 'cat-import',
                                                                           'nameIsAutoGenerated' => 1,
                                                                           'scope' => 'local',
                                                                           'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                         }, 'XML::Pastor::Schema::ComplexType' ),
                     'catListRecords|http://san.mibac.it/cat-import' => bless( {
                                                                               'attributeInfo' => {},
                                                                               'attributePrefix' => '_',
                                                                               'attributes' => [],
                                                                               'baseClasses' => [
                                                                                                  'XML::Pastor::ComplexType'
                                                                                                ],
                                                                               'class' => 'SAN::Cat::Type::catListRecords',
                                                                               'contentType' => 'complex',
                                                                               'elementInfo' => {
                                                                                                  'catRecord' => bless( {
                                                                                                                        'class' => 'SAN::Cat::Type::catRecord',
                                                                                                                        'maxOccurs' => 'unbounded',
                                                                                                                        'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                        'minOccurs' => '1',
                                                                                                                        'name' => 'catRecord',
                                                                                                                        'scope' => 'local',
                                                                                                                        'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                        'type' => 'catRecord|http://san.mibac.it/cat-import'
                                                                                                                      }, 'XML::Pastor::Schema::Element' )
                                                                                                },
                                                                               'elements' => [
                                                                                               'catRecord'
                                                                                             ],
                                                                               'isRedefinable' => 1,
                                                                               'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                               'name' => 'catListRecords',
                                                                               'scope' => 'global',
                                                                               'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                             }, 'XML::Pastor::Schema::ComplexType' ),
                     'catRecordBody|http://san.mibac.it/cat-import' => bless( {
                                                                              'attributeInfo' => {},
                                                                              'attributePrefix' => '_',
                                                                              'attributes' => [],
                                                                              'baseClasses' => [
                                                                                                 'XML::Pastor::ComplexType'
                                                                                               ],
                                                                              'class' => 'SAN::Cat::Type::catRecordBody',
                                                                              'contentType' => 'complex',
                                                                              'elementInfo' => {
                                                                                                 'eac-cpf' => bless( {
                                                                                                                     'class' => undef,
                                                                                                                     'definition' => undef,
                                                                                                                     'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                     'name' => 'eac-cpf',
                                                                                                                     'nameIsAutoGenerated' => 1,
                                                                                                                     'ref' => 'eac-cpf|http://san.mibac.it/eac-san/',
                                                                                                                     'scope' => 'local',
                                                                                                                     'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                                                                                   }, 'XML::Pastor::Schema::Element' ),
                                                                                                 'ead' => bless( {
                                                                                                                 'class' => 'SAN::EAD',
                                                                                                                 'definition' => undef,
                                                                                                                 'metaClass' => 'SAN::EAD::Pastor::Meta',
                                                                                                                 'name' => 'ead',
                                                                                                                 'nameIsAutoGenerated' => 1,
                                                                                                                 'ref' => 'ead|http://san.mibac.it/ricerca-san/',
                                                                                                                 'scope' => 'local',
                                                                                                                 'targetNamespace' => 'http://san.mibac.it/ricerca-san/'
                                                                                                               }, 'XML::Pastor::Schema::Element' ),
                                                                                                 'scons' => bless( {
                                                                                                                   'class' => undef,
                                                                                                                   'definition' => undef,
                                                                                                                   'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                   'name' => 'scons',
                                                                                                                   'nameIsAutoGenerated' => 1,
                                                                                                                   'ref' => 'scons|http://san.mibac.it/scons-san/',
                                                                                                                   'scope' => 'local',
                                                                                                                   'targetNamespace' => 'http://san.mibac.it/scons-san/'
                                                                                                                 }, 'XML::Pastor::Schema::Element' )
                                                                                               },
                                                                              'elements' => [
                                                                                              'ead',
                                                                                              'ead',
                                                                                              'eac-cpf',
                                                                                              'scons'
                                                                                            ],
                                                                              'isRedefinable' => 1,
                                                                              'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                              'name' => 'catRecordBody',
                                                                              'scope' => 'global',
                                                                              'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                            }, 'XML::Pastor::Schema::ComplexType' ),
                     'catRecordHeader_type|http://san.mibac.it/cat-import' => bless( {
                                                                                     'base' => 'string|http://www.w3.org/2001/XMLSchema',
                                                                                     'baseClasses' => [
                                                                                                        'XML::Pastor::Builtin::string'
                                                                                                      ],
                                                                                     'class' => 'SAN::Cat::Type::catRecordHeader_type',
                                                                                     'contentType' => 'simple',
                                                                                     'derivedBy' => 'restriction',
                                                                                     'enumeration' => {
                                                                                                        'complesso archivistico' => 1,
                                                                                                        'soggetto conservatore' => 1,
                                                                                                        'soggetto produttore' => 1,
                                                                                                        'strumento di ricerca' => 1
                                                                                                      },
                                                                                     'isRedefinable' => 1,
                                                                                     'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                     'name' => 'catRecordHeader_type',
                                                                                     'nameIsAutoGenerated' => 1,
                                                                                     'scope' => 'local',
                                                                                     'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                                   }, 'XML::Pastor::Schema::SimpleType' ),
                     'catRecordHeader|http://san.mibac.it/cat-import' => bless( {
                                                                                'attributeInfo' => {
                                                                                                     'status' => bless( {
                                                                                                                        'class' => undef,
                                                                                                                        'fixed' => 'deleted',
                                                                                                                        'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                        'name' => 'status',
                                                                                                                        'scope' => 'local',
                                                                                                                        'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                        'use' => 'optional'
                                                                                                                      }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                     'type' => bless( {
                                                                                                                      'class' => 'SAN::Cat::Type::catRecordHeader_type',
                                                                                                                      'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                      'name' => 'type',
                                                                                                                      'scope' => 'local',
                                                                                                                      'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                      'type' => 'catRecordHeader_type|http://san.mibac.it/cat-import',
                                                                                                                      'use' => 'required'
                                                                                                                    }, 'XML::Pastor::Schema::Attribute' )
                                                                                                   },
                                                                                'attributePrefix' => '_',
                                                                                'attributes' => [
                                                                                                  'status',
                                                                                                  'type'
                                                                                                ],
                                                                                'baseClasses' => [
                                                                                                   'XML::Pastor::ComplexType'
                                                                                                 ],
                                                                                'class' => 'SAN::Cat::Type::catRecordHeader',
                                                                                'contentType' => 'complex',
                                                                                'elementInfo' => {
                                                                                                   'id' => bless( {
                                                                                                                  'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                                                                                  'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                  'name' => 'id',
                                                                                                                  'scope' => 'local',
                                                                                                                  'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                  'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema'
                                                                                                                }, 'XML::Pastor::Schema::Element' ),
                                                                                                   'lastUpdate' => bless( {
                                                                                                                          'class' => 'XML::Pastor::Builtin::dateTime',
                                                                                                                          'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                          'name' => 'lastUpdate',
                                                                                                                          'scope' => 'local',
                                                                                                                          'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                          'type' => 'dateTime|http://www.w3.org/2001/XMLSchema'
                                                                                                                        }, 'XML::Pastor::Schema::Element' )
                                                                                                 },
                                                                                'elements' => [
                                                                                                'id',
                                                                                                'lastUpdate'
                                                                                              ],
                                                                                'isRedefinable' => 1,
                                                                                'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                'name' => 'catRecordHeader',
                                                                                'scope' => 'global',
                                                                                'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                              }, 'XML::Pastor::Schema::ComplexType' ),
                     'catRecord|http://san.mibac.it/cat-import' => bless( {
                                                                          'attributeInfo' => {},
                                                                          'attributePrefix' => '_',
                                                                          'attributes' => [],
                                                                          'baseClasses' => [
                                                                                             'XML::Pastor::ComplexType'
                                                                                           ],
                                                                          'class' => 'SAN::Cat::Type::catRecord',
                                                                          'contentType' => 'complex',
                                                                          'elementInfo' => {
                                                                                             'catRecordBody' => bless( {
                                                                                                                       'class' => 'SAN::Cat::Type::catRecordBody',
                                                                                                                       'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                       'minOccurs' => '0',
                                                                                                                       'name' => 'catRecordBody',
                                                                                                                       'scope' => 'local',
                                                                                                                       'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                       'type' => 'catRecordBody|http://san.mibac.it/cat-import'
                                                                                                                     }, 'XML::Pastor::Schema::Element' ),
                                                                                             'catRecordHeader' => bless( {
                                                                                                                         'class' => 'SAN::Cat::Type::catRecordHeader',
                                                                                                                         'maxOccurs' => '1',
                                                                                                                         'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                         'minOccurs' => '1',
                                                                                                                         'name' => 'catRecordHeader',
                                                                                                                         'scope' => 'local',
                                                                                                                         'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                         'type' => 'catRecordHeader|http://san.mibac.it/cat-import'
                                                                                                                       }, 'XML::Pastor::Schema::Element' )
                                                                                           },
                                                                          'elements' => [
                                                                                          'catRecordHeader',
                                                                                          'catRecordBody'
                                                                                        ],
                                                                          'isRedefinable' => 1,
                                                                          'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                          'name' => 'catRecord',
                                                                          'scope' => 'global',
                                                                          'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                        }, 'XML::Pastor::Schema::ComplexType' ),
                     'catheader|http://san.mibac.it/cat-import' => bless( {
                                                                          'attributeInfo' => {},
                                                                          'attributePrefix' => '_',
                                                                          'attributes' => [],
                                                                          'baseClasses' => [
                                                                                             'XML::Pastor::ComplexType'
                                                                                           ],
                                                                          'class' => 'SAN::Cat::Type::catheader',
                                                                          'contentType' => 'complex',
                                                                          'elementInfo' => {
                                                                                             'contact' => bless( {
                                                                                                                 'class' => 'SAN::Cat::Type::contact',
                                                                                                                 'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                 'name' => 'contact',
                                                                                                                 'scope' => 'local',
                                                                                                                 'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                 'type' => 'contact|http://san.mibac.it/cat-import'
                                                                                                               }, 'XML::Pastor::Schema::Element' ),
                                                                                             'filedesc' => bless( {
                                                                                                                  'class' => 'SAN::Cat::Type::filedesc',
                                                                                                                  'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                  'name' => 'filedesc',
                                                                                                                  'scope' => 'local',
                                                                                                                  'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                  'type' => 'filedesc|http://san.mibac.it/cat-import'
                                                                                                                }, 'XML::Pastor::Schema::Element' ),
                                                                                             'systemId' => bless( {
                                                                                                                  'class' => 'XML::Pastor::Builtin::string',
                                                                                                                  'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                  'name' => 'systemId',
                                                                                                                  'scope' => 'local',
                                                                                                                  'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                  'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                                                }, 'XML::Pastor::Schema::Element' )
                                                                                           },
                                                                          'elements' => [
                                                                                          'systemId',
                                                                                          'contact',
                                                                                          'filedesc'
                                                                                        ],
                                                                          'isRedefinable' => 1,
                                                                          'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                          'name' => 'catheader',
                                                                          'scope' => 'global',
                                                                          'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                        }, 'XML::Pastor::Schema::ComplexType' ),
                     'contact|http://san.mibac.it/cat-import' => bless( {
                                                                        'attributeInfo' => {},
                                                                        'attributePrefix' => '_',
                                                                        'attributes' => [],
                                                                        'baseClasses' => [
                                                                                           'XML::Pastor::ComplexType'
                                                                                         ],
                                                                        'class' => 'SAN::Cat::Type::contact',
                                                                        'contentType' => 'complex',
                                                                        'elementInfo' => {
                                                                                           'fax' => bless( {
                                                                                                           'class' => 'XML::Pastor::Builtin::string',
                                                                                                           'maxOccurs' => 'unbounded',
                                                                                                           'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                           'minOccurs' => '0',
                                                                                                           'name' => 'fax',
                                                                                                           'scope' => 'local',
                                                                                                           'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                           'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                                         }, 'XML::Pastor::Schema::Element' ),
                                                                                           'mail' => bless( {
                                                                                                            'class' => 'XML::Pastor::Builtin::string',
                                                                                                            'maxOccurs' => 'unbounded',
                                                                                                            'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                            'minOccurs' => '1',
                                                                                                            'name' => 'mail',
                                                                                                            'scope' => 'local',
                                                                                                            'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                            'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                                          }, 'XML::Pastor::Schema::Element' ),
                                                                                           'name' => bless( {
                                                                                                            'class' => 'XML::Pastor::Builtin::string',
                                                                                                            'maxOccurs' => 'unbounded',
                                                                                                            'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                            'minOccurs' => '0',
                                                                                                            'name' => 'name',
                                                                                                            'scope' => 'local',
                                                                                                            'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                            'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                                          }, 'XML::Pastor::Schema::Element' ),
                                                                                           'phone' => bless( {
                                                                                                             'class' => 'XML::Pastor::Builtin::string',
                                                                                                             'maxOccurs' => 'unbounded',
                                                                                                             'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                             'minOccurs' => '0',
                                                                                                             'name' => 'phone',
                                                                                                             'scope' => 'local',
                                                                                                             'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                             'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                                           }, 'XML::Pastor::Schema::Element' )
                                                                                         },
                                                                        'elements' => [
                                                                                        'name',
                                                                                        'mail',
                                                                                        'phone',
                                                                                        'fax'
                                                                                      ],
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                        'name' => 'contact',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                      }, 'XML::Pastor::Schema::ComplexType' ),
                     'filedesc|http://san.mibac.it/cat-import' => bless( {
                                                                         'attributeInfo' => {},
                                                                         'attributePrefix' => '_',
                                                                         'attributes' => [],
                                                                         'baseClasses' => [
                                                                                            'XML::Pastor::ComplexType'
                                                                                          ],
                                                                         'class' => 'SAN::Cat::Type::filedesc',
                                                                         'contentType' => 'complex',
                                                                         'elementInfo' => {
                                                                                            'abstract' => bless( {
                                                                                                                 'class' => 'XML::Pastor::Builtin::string',
                                                                                                                 'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                                 'minOccurs' => '0',
                                                                                                                 'name' => 'abstract',
                                                                                                                 'scope' => 'local',
                                                                                                                 'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                                 'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                                               }, 'XML::Pastor::Schema::Element' ),
                                                                                            'date' => bless( {
                                                                                                             'class' => 'XML::Pastor::Builtin::dateTime',
                                                                                                             'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                             'name' => 'date',
                                                                                                             'scope' => 'local',
                                                                                                             'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                             'type' => 'dateTime|http://www.w3.org/2001/XMLSchema'
                                                                                                           }, 'XML::Pastor::Schema::Element' ),
                                                                                            'title' => bless( {
                                                                                                              'class' => 'XML::Pastor::Builtin::string',
                                                                                                              'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                                                              'name' => 'title',
                                                                                                              'scope' => 'local',
                                                                                                              'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                                                                              'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                                                                            }, 'XML::Pastor::Schema::Element' )
                                                                                          },
                                                                         'elements' => [
                                                                                         'title',
                                                                                         'abstract',
                                                                                         'date'
                                                                                       ],
                                                                         'isRedefinable' => 1,
                                                                         'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                                         'name' => 'filedesc',
                                                                         'scope' => 'global',
                                                                         'targetNamespace' => 'http://san.mibac.it/cat-import'
                                                                       }, 'XML::Pastor::Schema::ComplexType' ),
	 }
				      
       }, 'XML::Pastor::Schema::Model' ) );

1;
