
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::ns002::Type::arcType;

use SAN::EAC::ns002::Type::actuateType;
use SAN::EAC::ns002::Type::arcroleType;
use SAN::EAC::ns002::Type::fromType;
use SAN::EAC::ns002::Type::showType;
use SAN::EAC::ns002::Type::titleAttrType;
use SAN::EAC::ns002::Type::titleEltType;
use SAN::EAC::ns002::Type::toType;
use SAN::EAC::ns002::Type::typeType;
use SAN::EAC::ns002::title;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::ns002::Type::arcType->mk_accessors( qw(_type _arcrole _title _show _actuate _from _to title));

# Attribute accessor aliases

sub type { &_type; }
sub arcrole { &_arcrole; }
sub show { &_show; }
sub actuate { &_actuate; }
sub from { &_from; }
sub to { &_to; }

SAN::EAC::ns002::Type::arcType->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'actuate' => bless( {
                                                  'class' => 'SAN::EAC::ns002::Type::actuateType',
                                                  'definition' => bless( {
                                                                           'class' => 'SAN::EAC::ns002::Type::actuateType',
                                                                           'isRedefinable' => 1,
                                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                           'name' => 'actuate',
                                                                           'scope' => 'global',
                                                                           'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                           'type' => 'actuateType|http://www.w3.org/1999/xlink'
                                                                         }, 'XML::Pastor::Schema::Attribute' ),
                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                  'name' => 'actuate',
                                                  'nameIsAutoGenerated' => 1,
                                                  'ref' => 'actuate|http://www.w3.org/1999/xlink',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                }, 'XML::Pastor::Schema::Attribute' ),
                              'arcAttrs' => bless( {
                                                   'attributeInfo' => {},
                                                   'attributes' => [],
                                                   'class' => undef,
                                                   'contentType' => 'attributeGroup',
                                                   'definition' => bless( {
                                                                            'attributeInfo' => {
                                                                                                 'actuate' => bless( {
                                                                                                                     'class' => 'SAN::EAC::ns002::Type::actuateType',
                                                                                                                     'definition' => bless( {
                                                                                                                                              'class' => 'SAN::EAC::ns002::Type::actuateType',
                                                                                                                                              'isRedefinable' => 1,
                                                                                                                                              'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                              'name' => 'actuate',
                                                                                                                                              'scope' => 'global',
                                                                                                                                              'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                              'type' => 'actuateType|http://www.w3.org/1999/xlink'
                                                                                                                                            }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                     'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                     'name' => 'actuate',
                                                                                                                     'nameIsAutoGenerated' => 1,
                                                                                                                     'ref' => 'actuate|http://www.w3.org/1999/xlink',
                                                                                                                     'scope' => 'local',
                                                                                                                     'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                   }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                 'arcrole' => bless( {
                                                                                                                     'class' => 'SAN::EAC::ns002::Type::arcroleType',
                                                                                                                     'definition' => bless( {
                                                                                                                                              'class' => 'SAN::EAC::ns002::Type::arcroleType',
                                                                                                                                              'isRedefinable' => 1,
                                                                                                                                              'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                              'name' => 'arcrole',
                                                                                                                                              'scope' => 'global',
                                                                                                                                              'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                              'type' => 'arcroleType|http://www.w3.org/1999/xlink'
                                                                                                                                            }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                     'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                     'name' => 'arcrole',
                                                                                                                     'nameIsAutoGenerated' => 1,
                                                                                                                     'ref' => 'arcrole|http://www.w3.org/1999/xlink',
                                                                                                                     'scope' => 'local',
                                                                                                                     'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                   }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                 'from' => bless( {
                                                                                                                  'class' => 'SAN::EAC::ns002::Type::fromType',
                                                                                                                  'definition' => bless( {
                                                                                                                                           'class' => 'SAN::EAC::ns002::Type::fromType',
                                                                                                                                           'isRedefinable' => 1,
                                                                                                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                           'name' => 'from',
                                                                                                                                           'scope' => 'global',
                                                                                                                                           'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                           'type' => 'fromType|http://www.w3.org/1999/xlink'
                                                                                                                                         }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                  'name' => 'from',
                                                                                                                  'nameIsAutoGenerated' => 1,
                                                                                                                  'ref' => 'from|http://www.w3.org/1999/xlink',
                                                                                                                  'scope' => 'local',
                                                                                                                  'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                 'show' => bless( {
                                                                                                                  'class' => 'SAN::EAC::ns002::Type::showType',
                                                                                                                  'definition' => bless( {
                                                                                                                                           'class' => 'SAN::EAC::ns002::Type::showType',
                                                                                                                                           'isRedefinable' => 1,
                                                                                                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                           'name' => 'show',
                                                                                                                                           'scope' => 'global',
                                                                                                                                           'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                           'type' => 'showType|http://www.w3.org/1999/xlink'
                                                                                                                                         }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                  'name' => 'show',
                                                                                                                  'nameIsAutoGenerated' => 1,
                                                                                                                  'ref' => 'show|http://www.w3.org/1999/xlink',
                                                                                                                  'scope' => 'local',
                                                                                                                  'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                 'title' => bless( {
                                                                                                                   'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                                                                                   'definition' => bless( {
                                                                                                                                            'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                                                                                                            'isRedefinable' => 1,
                                                                                                                                            'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                            'name' => 'title',
                                                                                                                                            'scope' => 'global',
                                                                                                                                            'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                            'type' => 'titleAttrType|http://www.w3.org/1999/xlink'
                                                                                                                                          }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                   'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                   'name' => 'title',
                                                                                                                   'nameIsAutoGenerated' => 1,
                                                                                                                   'ref' => 'title|http://www.w3.org/1999/xlink',
                                                                                                                   'scope' => 'local',
                                                                                                                   'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                 }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                 'to' => bless( {
                                                                                                                'class' => 'SAN::EAC::ns002::Type::toType',
                                                                                                                'definition' => bless( {
                                                                                                                                         'class' => 'SAN::EAC::ns002::Type::toType',
                                                                                                                                         'isRedefinable' => 1,
                                                                                                                                         'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                         'name' => 'to',
                                                                                                                                         'scope' => 'global',
                                                                                                                                         'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                         'type' => 'toType|http://www.w3.org/1999/xlink'
                                                                                                                                       }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                'documentation' => bless( [
                                                                                                                                            bless( {
                                                                                                                                                     'text' => '
     from and to have default behavior when values are missing
    '
                                                                                                                                                   }, 'XML::Pastor::Schema::Documentation' )
                                                                                                                                          ], 'Data::HashArray' ),
                                                                                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                'name' => 'to',
                                                                                                                'nameIsAutoGenerated' => 1,
                                                                                                                'ref' => 'to|http://www.w3.org/1999/xlink',
                                                                                                                'scope' => 'local',
                                                                                                                'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                              }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                 'type' => bless( {
                                                                                                                  'class' => 'SAN::EAC::ns002::Type::typeType',
                                                                                                                  'definition' => bless( {
                                                                                                                                           'class' => 'SAN::EAC::ns002::Type::typeType',
                                                                                                                                           'isRedefinable' => 1,
                                                                                                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                           'name' => 'type',
                                                                                                                                           'scope' => 'global',
                                                                                                                                           'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                           'type' => 'typeType|http://www.w3.org/1999/xlink'
                                                                                                                                         }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                  'fixed' => 'arc',
                                                                                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                  'name' => 'type',
                                                                                                                  'nameIsAutoGenerated' => 1,
                                                                                                                  'ref' => 'type|http://www.w3.org/1999/xlink',
                                                                                                                  'scope' => 'local',
                                                                                                                  'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                  'use' => 'required'
                                                                                                                }, 'XML::Pastor::Schema::Attribute' )
                                                                                               },
                                                                            'attributes' => [
                                                                                              'type',
                                                                                              'arcrole',
                                                                                              'title',
                                                                                              'show',
                                                                                              'actuate',
                                                                                              'from',
                                                                                              'to'
                                                                                            ],
                                                                            'class' => undef,
                                                                            'contentType' => 'attributeGroup',
                                                                            'isRedefinable' => 1,
                                                                            'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                            'name' => 'arcAttrs',
                                                                            'scope' => 'global',
                                                                            'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                          }, 'XML::Pastor::Schema::AttributeGroup' ),
                                                   'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                   'name' => 'arcAttrs',
                                                   'nameIsAutoGenerated' => 1,
                                                   'ref' => 'arcAttrs|http://www.w3.org/1999/xlink',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                 }, 'XML::Pastor::Schema::AttributeGroup' ),
                              'arcrole' => bless( {
                                                  'class' => 'SAN::EAC::ns002::Type::arcroleType',
                                                  'definition' => bless( {
                                                                           'class' => 'SAN::EAC::ns002::Type::arcroleType',
                                                                           'isRedefinable' => 1,
                                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                           'name' => 'arcrole',
                                                                           'scope' => 'global',
                                                                           'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                           'type' => 'arcroleType|http://www.w3.org/1999/xlink'
                                                                         }, 'XML::Pastor::Schema::Attribute' ),
                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                  'name' => 'arcrole',
                                                  'nameIsAutoGenerated' => 1,
                                                  'ref' => 'arcrole|http://www.w3.org/1999/xlink',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                }, 'XML::Pastor::Schema::Attribute' ),
                              'from' => bless( {
                                               'class' => 'SAN::EAC::ns002::Type::fromType',
                                               'definition' => bless( {
                                                                        'class' => 'SAN::EAC::ns002::Type::fromType',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                        'name' => 'from',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                        'type' => 'fromType|http://www.w3.org/1999/xlink'
                                                                      }, 'XML::Pastor::Schema::Attribute' ),
                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                               'name' => 'from',
                                               'nameIsAutoGenerated' => 1,
                                               'ref' => 'from|http://www.w3.org/1999/xlink',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                             }, 'XML::Pastor::Schema::Attribute' ),
                              'show' => bless( {
                                               'class' => 'SAN::EAC::ns002::Type::showType',
                                               'definition' => bless( {
                                                                        'class' => 'SAN::EAC::ns002::Type::showType',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                        'name' => 'show',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                        'type' => 'showType|http://www.w3.org/1999/xlink'
                                                                      }, 'XML::Pastor::Schema::Attribute' ),
                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                               'name' => 'show',
                                               'nameIsAutoGenerated' => 1,
                                               'ref' => 'show|http://www.w3.org/1999/xlink',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                             }, 'XML::Pastor::Schema::Attribute' ),
                              'title' => bless( {
                                                'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                'definition' => bless( {
                                                                         'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                                         'isRedefinable' => 1,
                                                                         'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                         'name' => 'title',
                                                                         'scope' => 'global',
                                                                         'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                         'type' => 'titleAttrType|http://www.w3.org/1999/xlink'
                                                                       }, 'XML::Pastor::Schema::Attribute' ),
                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                'name' => 'title',
                                                'nameIsAutoGenerated' => 1,
                                                'ref' => 'title|http://www.w3.org/1999/xlink',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                              }, 'XML::Pastor::Schema::Attribute' ),
                              'to' => bless( {
                                             'class' => 'SAN::EAC::ns002::Type::toType',
                                             'definition' => bless( {
                                                                      'class' => 'SAN::EAC::ns002::Type::toType',
                                                                      'isRedefinable' => 1,
                                                                      'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                      'name' => 'to',
                                                                      'scope' => 'global',
                                                                      'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                      'type' => 'toType|http://www.w3.org/1999/xlink'
                                                                    }, 'XML::Pastor::Schema::Attribute' ),
                                             'documentation' => bless( [
                                                                         bless( {
                                                                                  'text' => '
     from and to have default behavior when values are missing
    '
                                                                                }, 'XML::Pastor::Schema::Documentation' )
                                                                       ], 'Data::HashArray' ),
                                             'metaClass' => 'SAN::EAC::Pastor::Meta',
                                             'name' => 'to',
                                             'nameIsAutoGenerated' => 1,
                                             'ref' => 'to|http://www.w3.org/1999/xlink',
                                             'scope' => 'local',
                                             'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                           }, 'XML::Pastor::Schema::Attribute' ),
                              'type' => bless( {
                                               'class' => 'SAN::EAC::ns002::Type::typeType',
                                               'definition' => bless( {
                                                                        'class' => 'SAN::EAC::ns002::Type::typeType',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                        'name' => 'type',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                        'type' => 'typeType|http://www.w3.org/1999/xlink'
                                                                      }, 'XML::Pastor::Schema::Attribute' ),
                                               'fixed' => 'arc',
                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                               'name' => 'type',
                                               'nameIsAutoGenerated' => 1,
                                               'ref' => 'type|http://www.w3.org/1999/xlink',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                               'use' => 'required'
                                             }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'type',
                           'arcrole',
                           'title',
                           'show',
                           'actuate',
                           'from',
                           'to'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::ns002::Type::arcType',
         'contentType' => 'complex',
         'elementInfo' => {
                            'arcModel' => bless( {
                                                 'class' => undef,
                                                 'contentType' => 'group',
                                                 'definition' => bless( {
                                                                          'class' => undef,
                                                                          'contentType' => 'group',
                                                                          'elementInfo' => {
                                                                                             'title' => bless( {
                                                                                                               'class' => 'SAN::EAC::ns002::Type::titleEltType',
                                                                                                               'definition' => bless( {
                                                                                                                                        'abstract' => 'true',
                                                                                                                                        'baseClasses' => [
                                                                                                                                                           'SAN::EAC::ns002::Type::titleEltType',
                                                                                                                                                           'XML::Pastor::Element'
                                                                                                                                                         ],
                                                                                                                                        'class' => 'SAN::EAC::ns002::title',
                                                                                                                                        'isRedefinable' => 1,
                                                                                                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                        'name' => 'title',
                                                                                                                                        'scope' => 'global',
                                                                                                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                        'type' => 'titleEltType|http://www.w3.org/1999/xlink'
                                                                                                                                      }, 'XML::Pastor::Schema::Element' ),
                                                                                                               'maxOccurs' => 'unbounded',
                                                                                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                               'minOccurs' => '0',
                                                                                                               'name' => 'title',
                                                                                                               'nameIsAutoGenerated' => 1,
                                                                                                               'ref' => 'title|http://www.w3.org/1999/xlink',
                                                                                                               'scope' => 'local',
                                                                                                               'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                             }, 'XML::Pastor::Schema::Element' )
                                                                                           },
                                                                          'elements' => [
                                                                                          'title'
                                                                                        ],
                                                                          'isRedefinable' => 1,
                                                                          'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                          'name' => 'arcModel',
                                                                          'scope' => 'global',
                                                                          'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                        }, 'XML::Pastor::Schema::Group' ),
                                                 'elementInfo' => {},
                                                 'elements' => [],
                                                 'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                 'name' => 'arcModel',
                                                 'nameIsAutoGenerated' => 1,
                                                 'ref' => 'arcModel|http://www.w3.org/1999/xlink',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                               }, 'XML::Pastor::Schema::Group' ),
                            'title' => bless( {
                                              'class' => 'SAN::EAC::ns002::Type::titleEltType',
                                              'definition' => bless( {
                                                                       'abstract' => 'true',
                                                                       'baseClasses' => [
                                                                                          'SAN::EAC::ns002::Type::titleEltType',
                                                                                          'XML::Pastor::Element'
                                                                                        ],
                                                                       'class' => 'SAN::EAC::ns002::title',
                                                                       'isRedefinable' => 1,
                                                                       'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                       'name' => 'title',
                                                                       'scope' => 'global',
                                                                       'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                       'type' => 'titleEltType|http://www.w3.org/1999/xlink'
                                                                     }, 'XML::Pastor::Schema::Element' ),
                                              'maxOccurs' => 'unbounded',
                                              'metaClass' => 'SAN::EAC::Pastor::Meta',
                                              'minOccurs' => '0',
                                              'name' => 'title',
                                              'nameIsAutoGenerated' => 1,
                                              'ref' => 'title|http://www.w3.org/1999/xlink',
                                              'scope' => 'local',
                                              'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                            }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'title'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'arcType',
         'scope' => 'global',
         'targetNamespace' => 'http://www.w3.org/1999/xlink'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::ns002::Type::arcType>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_actuate>(), B<actuate>()      - See L<SAN::EAC::ns002::Type::actuateType>.

=item B<_arcrole>(), B<arcrole>()      - See L<SAN::EAC::ns002::Type::arcroleType>.

=item B<_from>(), B<from>()      - See L<SAN::EAC::ns002::Type::fromType>.

=item B<_show>(), B<show>()      - See L<SAN::EAC::ns002::Type::showType>.

=item B<_title>()      - See L<SAN::EAC::ns002::Type::titleAttrType>.

=item B<_to>(), B<to>()      - See L<SAN::EAC::ns002::Type::toType>.

=item B<_type>(), B<type>()      - See L<SAN::EAC::ns002::Type::typeType>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<title>()      - See L<SAN::EAC::ns002::Type::titleEltType>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
