
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::ns002::Type::extended;

use SAN::EAC::ns002::Type::arcType;
use SAN::EAC::ns002::Type::locatorType;
use SAN::EAC::ns002::Type::resourceType;
use SAN::EAC::ns002::Type::roleType;
use SAN::EAC::ns002::Type::titleAttrType;
use SAN::EAC::ns002::Type::titleEltType;
use SAN::EAC::ns002::Type::typeType;
use SAN::EAC::ns002::arc;
use SAN::EAC::ns002::locator;
use SAN::EAC::ns002::resource;
use SAN::EAC::ns002::title;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::ns002::Type::extended->mk_accessors( qw(_type _role _title title resource locator arc));

# Attribute accessor aliases

sub type { &_type; }
sub role { &_role; }

SAN::EAC::ns002::Type::extended->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'extendedAttrs' => bless( {
                                                        'attributeInfo' => {},
                                                        'attributes' => [],
                                                        'class' => undef,
                                                        'contentType' => 'attributeGroup',
                                                        'definition' => bless( {
                                                                                 'attributeInfo' => {
                                                                                                      'role' => bless( {
                                                                                                                       'class' => 'SAN::EAC::ns002::Type::roleType',
                                                                                                                       'definition' => bless( {
                                                                                                                                                'class' => 'SAN::EAC::ns002::Type::roleType',
                                                                                                                                                'isRedefinable' => 1,
                                                                                                                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                                'name' => 'role',
                                                                                                                                                'scope' => 'global',
                                                                                                                                                'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                                'type' => 'roleType|http://www.w3.org/1999/xlink'
                                                                                                                                              }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                       'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                       'name' => 'role',
                                                                                                                       'nameIsAutoGenerated' => 1,
                                                                                                                       'ref' => 'role|http://www.w3.org/1999/xlink',
                                                                                                                       'scope' => 'local',
                                                                                                                       'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                     }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                      'title' => bless( {
                                                                                                                        'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                                                                                        'definition' => bless( {
                                                                                                                                                 'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                                                                                                                 'isRedefinable' => 1,
                                                                                                                                                 'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                                 'name' => 'title',
                                                                                                                                                 'scope' => 'global',
                                                                                                                                                 'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                                 'type' => 'titleAttrType|http://www.w3.org/1999/xlink'
                                                                                                                                               }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                        'name' => 'title',
                                                                                                                        'nameIsAutoGenerated' => 1,
                                                                                                                        'ref' => 'title|http://www.w3.org/1999/xlink',
                                                                                                                        'scope' => 'local',
                                                                                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                      }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                      'type' => bless( {
                                                                                                                       'class' => 'SAN::EAC::ns002::Type::typeType',
                                                                                                                       'definition' => bless( {
                                                                                                                                                'class' => 'SAN::EAC::ns002::Type::typeType',
                                                                                                                                                'isRedefinable' => 1,
                                                                                                                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                                'name' => 'type',
                                                                                                                                                'scope' => 'global',
                                                                                                                                                'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                                'type' => 'typeType|http://www.w3.org/1999/xlink'
                                                                                                                                              }, 'XML::Pastor::Schema::Attribute' ),
                                                                                                                       'fixed' => 'extended',
                                                                                                                       'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                       'name' => 'type',
                                                                                                                       'nameIsAutoGenerated' => 1,
                                                                                                                       'ref' => 'type|http://www.w3.org/1999/xlink',
                                                                                                                       'scope' => 'local',
                                                                                                                       'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                       'use' => 'required'
                                                                                                                     }, 'XML::Pastor::Schema::Attribute' )
                                                                                                    },
                                                                                 'attributes' => [
                                                                                                   'type',
                                                                                                   'role',
                                                                                                   'title'
                                                                                                 ],
                                                                                 'class' => undef,
                                                                                 'contentType' => 'attributeGroup',
                                                                                 'isRedefinable' => 1,
                                                                                 'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                 'name' => 'extendedAttrs',
                                                                                 'scope' => 'global',
                                                                                 'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                               }, 'XML::Pastor::Schema::AttributeGroup' ),
                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                        'name' => 'extendedAttrs',
                                                        'nameIsAutoGenerated' => 1,
                                                        'ref' => 'extendedAttrs|http://www.w3.org/1999/xlink',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                      }, 'XML::Pastor::Schema::AttributeGroup' ),
                              'role' => bless( {
                                               'class' => 'SAN::EAC::ns002::Type::roleType',
                                               'definition' => bless( {
                                                                        'class' => 'SAN::EAC::ns002::Type::roleType',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                        'name' => 'role',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                        'type' => 'roleType|http://www.w3.org/1999/xlink'
                                                                      }, 'XML::Pastor::Schema::Attribute' ),
                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                               'name' => 'role',
                                               'nameIsAutoGenerated' => 1,
                                               'ref' => 'role|http://www.w3.org/1999/xlink',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                             }, 'XML::Pastor::Schema::Attribute' ),
                              'title' => bless( {
                                                'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                'definition' => bless( {
                                                                         'class' => 'SAN::EAC::ns002::Type::titleAttrType',
                                                                         'isRedefinable' => 1,
                                                                         'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                         'name' => 'title',
                                                                         'scope' => 'global',
                                                                         'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                         'type' => 'titleAttrType|http://www.w3.org/1999/xlink'
                                                                       }, 'XML::Pastor::Schema::Attribute' ),
                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                'name' => 'title',
                                                'nameIsAutoGenerated' => 1,
                                                'ref' => 'title|http://www.w3.org/1999/xlink',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                              }, 'XML::Pastor::Schema::Attribute' ),
                              'type' => bless( {
                                               'class' => 'SAN::EAC::ns002::Type::typeType',
                                               'definition' => bless( {
                                                                        'class' => 'SAN::EAC::ns002::Type::typeType',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                        'name' => 'type',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                        'type' => 'typeType|http://www.w3.org/1999/xlink'
                                                                      }, 'XML::Pastor::Schema::Attribute' ),
                                               'fixed' => 'extended',
                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                               'name' => 'type',
                                               'nameIsAutoGenerated' => 1,
                                               'ref' => 'type|http://www.w3.org/1999/xlink',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                               'use' => 'required'
                                             }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'type',
                           'role',
                           'title'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::ns002::Type::extended',
         'contentType' => 'complex',
         'documentation' => bless( [
                                     bless( {
                                              'text' => '
    Intended for use as the type of user-declared elements to make them
    extended links.
    Note that the elements referenced in the content model are all abstract.
    The intention is that by simply declaring elements with these as their
    substitutionGroup, all the right things will happen.
   '
                                            }, 'XML::Pastor::Schema::Documentation' )
                                   ], 'Data::HashArray' ),
         'elementInfo' => {
                            'arc' => bless( {
                                            'class' => 'SAN::EAC::ns002::Type::arcType',
                                            'definition' => bless( {
                                                                     'abstract' => 'true',
                                                                     'baseClasses' => [
                                                                                        'SAN::EAC::ns002::Type::arcType',
                                                                                        'XML::Pastor::Element'
                                                                                      ],
                                                                     'class' => 'SAN::EAC::ns002::arc',
                                                                     'isRedefinable' => 1,
                                                                     'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                     'name' => 'arc',
                                                                     'scope' => 'global',
                                                                     'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                     'type' => 'arcType|http://www.w3.org/1999/xlink'
                                                                   }, 'XML::Pastor::Schema::Element' ),
                                            'metaClass' => 'SAN::EAC::Pastor::Meta',
                                            'name' => 'arc',
                                            'nameIsAutoGenerated' => 1,
                                            'ref' => 'arc|http://www.w3.org/1999/xlink',
                                            'scope' => 'local',
                                            'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                          }, 'XML::Pastor::Schema::Element' ),
                            'extendedModel' => bless( {
                                                      'class' => undef,
                                                      'contentType' => 'group',
                                                      'definition' => bless( {
                                                                               'class' => undef,
                                                                               'contentType' => 'group',
                                                                               'elementInfo' => {
                                                                                                  'arc' => bless( {
                                                                                                                  'class' => 'SAN::EAC::ns002::Type::arcType',
                                                                                                                  'definition' => bless( {
                                                                                                                                           'abstract' => 'true',
                                                                                                                                           'baseClasses' => [
                                                                                                                                                              'SAN::EAC::ns002::Type::arcType',
                                                                                                                                                              'XML::Pastor::Element'
                                                                                                                                                            ],
                                                                                                                                           'class' => 'SAN::EAC::ns002::arc',
                                                                                                                                           'isRedefinable' => 1,
                                                                                                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                           'name' => 'arc',
                                                                                                                                           'scope' => 'global',
                                                                                                                                           'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                           'type' => 'arcType|http://www.w3.org/1999/xlink'
                                                                                                                                         }, 'XML::Pastor::Schema::Element' ),
                                                                                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                  'name' => 'arc',
                                                                                                                  'nameIsAutoGenerated' => 1,
                                                                                                                  'ref' => 'arc|http://www.w3.org/1999/xlink',
                                                                                                                  'scope' => 'local',
                                                                                                                  'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                }, 'XML::Pastor::Schema::Element' ),
                                                                                                  'locator' => bless( {
                                                                                                                      'class' => 'SAN::EAC::ns002::Type::locatorType',
                                                                                                                      'definition' => bless( {
                                                                                                                                               'abstract' => 'true',
                                                                                                                                               'baseClasses' => [
                                                                                                                                                                  'SAN::EAC::ns002::Type::locatorType',
                                                                                                                                                                  'XML::Pastor::Element'
                                                                                                                                                                ],
                                                                                                                                               'class' => 'SAN::EAC::ns002::locator',
                                                                                                                                               'isRedefinable' => 1,
                                                                                                                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                               'name' => 'locator',
                                                                                                                                               'scope' => 'global',
                                                                                                                                               'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                               'type' => 'locatorType|http://www.w3.org/1999/xlink'
                                                                                                                                             }, 'XML::Pastor::Schema::Element' ),
                                                                                                                      'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                      'name' => 'locator',
                                                                                                                      'nameIsAutoGenerated' => 1,
                                                                                                                      'ref' => 'locator|http://www.w3.org/1999/xlink',
                                                                                                                      'scope' => 'local',
                                                                                                                      'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                    }, 'XML::Pastor::Schema::Element' ),
                                                                                                  'resource' => bless( {
                                                                                                                       'class' => 'SAN::EAC::ns002::Type::resourceType',
                                                                                                                       'definition' => bless( {
                                                                                                                                                'abstract' => 'true',
                                                                                                                                                'baseClasses' => [
                                                                                                                                                                   'SAN::EAC::ns002::Type::resourceType',
                                                                                                                                                                   'XML::Pastor::Element'
                                                                                                                                                                 ],
                                                                                                                                                'class' => 'SAN::EAC::ns002::resource',
                                                                                                                                                'isRedefinable' => 1,
                                                                                                                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                                'name' => 'resource',
                                                                                                                                                'scope' => 'global',
                                                                                                                                                'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                                'type' => 'resourceType|http://www.w3.org/1999/xlink'
                                                                                                                                              }, 'XML::Pastor::Schema::Element' ),
                                                                                                                       'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                       'name' => 'resource',
                                                                                                                       'nameIsAutoGenerated' => 1,
                                                                                                                       'ref' => 'resource|http://www.w3.org/1999/xlink',
                                                                                                                       'scope' => 'local',
                                                                                                                       'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                     }, 'XML::Pastor::Schema::Element' ),
                                                                                                  'title' => bless( {
                                                                                                                    'class' => 'SAN::EAC::ns002::Type::titleEltType',
                                                                                                                    'definition' => bless( {
                                                                                                                                             'abstract' => 'true',
                                                                                                                                             'baseClasses' => [
                                                                                                                                                                'SAN::EAC::ns002::Type::titleEltType',
                                                                                                                                                                'XML::Pastor::Element'
                                                                                                                                                              ],
                                                                                                                                             'class' => 'SAN::EAC::ns002::title',
                                                                                                                                             'isRedefinable' => 1,
                                                                                                                                             'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                                             'name' => 'title',
                                                                                                                                             'scope' => 'global',
                                                                                                                                             'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                                                                                             'type' => 'titleEltType|http://www.w3.org/1999/xlink'
                                                                                                                                           }, 'XML::Pastor::Schema::Element' ),
                                                                                                                    'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                                                    'name' => 'title',
                                                                                                                    'nameIsAutoGenerated' => 1,
                                                                                                                    'ref' => 'title|http://www.w3.org/1999/xlink',
                                                                                                                    'scope' => 'local',
                                                                                                                    'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                                                                  }, 'XML::Pastor::Schema::Element' )
                                                                                                },
                                                                               'elements' => [
                                                                                               'title',
                                                                                               'resource',
                                                                                               'locator',
                                                                                               'arc'
                                                                                             ],
                                                                               'isRedefinable' => 1,
                                                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                               'name' => 'extendedModel',
                                                                               'scope' => 'global',
                                                                               'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                                             }, 'XML::Pastor::Schema::Group' ),
                                                      'elementInfo' => {},
                                                      'elements' => [],
                                                      'maxOccurs' => 'unbounded',
                                                      'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'extendedModel',
                                                      'nameIsAutoGenerated' => 1,
                                                      'ref' => 'extendedModel|http://www.w3.org/1999/xlink',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                                    }, 'XML::Pastor::Schema::Group' ),
                            'locator' => bless( {
                                                'class' => 'SAN::EAC::ns002::Type::locatorType',
                                                'definition' => bless( {
                                                                         'abstract' => 'true',
                                                                         'baseClasses' => [
                                                                                            'SAN::EAC::ns002::Type::locatorType',
                                                                                            'XML::Pastor::Element'
                                                                                          ],
                                                                         'class' => 'SAN::EAC::ns002::locator',
                                                                         'isRedefinable' => 1,
                                                                         'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                         'name' => 'locator',
                                                                         'scope' => 'global',
                                                                         'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                         'type' => 'locatorType|http://www.w3.org/1999/xlink'
                                                                       }, 'XML::Pastor::Schema::Element' ),
                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                'name' => 'locator',
                                                'nameIsAutoGenerated' => 1,
                                                'ref' => 'locator|http://www.w3.org/1999/xlink',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                              }, 'XML::Pastor::Schema::Element' ),
                            'resource' => bless( {
                                                 'class' => 'SAN::EAC::ns002::Type::resourceType',
                                                 'definition' => bless( {
                                                                          'abstract' => 'true',
                                                                          'baseClasses' => [
                                                                                             'SAN::EAC::ns002::Type::resourceType',
                                                                                             'XML::Pastor::Element'
                                                                                           ],
                                                                          'class' => 'SAN::EAC::ns002::resource',
                                                                          'isRedefinable' => 1,
                                                                          'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                          'name' => 'resource',
                                                                          'scope' => 'global',
                                                                          'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                          'type' => 'resourceType|http://www.w3.org/1999/xlink'
                                                                        }, 'XML::Pastor::Schema::Element' ),
                                                 'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                 'name' => 'resource',
                                                 'nameIsAutoGenerated' => 1,
                                                 'ref' => 'resource|http://www.w3.org/1999/xlink',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                               }, 'XML::Pastor::Schema::Element' ),
                            'title' => bless( {
                                              'class' => 'SAN::EAC::ns002::Type::titleEltType',
                                              'definition' => bless( {
                                                                       'abstract' => 'true',
                                                                       'baseClasses' => [
                                                                                          'SAN::EAC::ns002::Type::titleEltType',
                                                                                          'XML::Pastor::Element'
                                                                                        ],
                                                                       'class' => 'SAN::EAC::ns002::title',
                                                                       'isRedefinable' => 1,
                                                                       'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                       'name' => 'title',
                                                                       'scope' => 'global',
                                                                       'targetNamespace' => 'http://www.w3.org/1999/xlink',
                                                                       'type' => 'titleEltType|http://www.w3.org/1999/xlink'
                                                                     }, 'XML::Pastor::Schema::Element' ),
                                              'metaClass' => 'SAN::EAC::Pastor::Meta',
                                              'name' => 'title',
                                              'nameIsAutoGenerated' => 1,
                                              'ref' => 'title|http://www.w3.org/1999/xlink',
                                              'scope' => 'local',
                                              'targetNamespace' => 'http://www.w3.org/1999/xlink'
                                            }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'title',
                         'resource',
                         'locator',
                         'arc'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'extended',
         'scope' => 'global',
         'targetNamespace' => 'http://www.w3.org/1999/xlink'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::ns002::Type::extended>  -  A class generated by L<XML::Pastor> . 


=head1 DESCRIPTION

Intended for use as the type of user-declared elements to make them
    extended links.
    Note that the elements referenced in the content model are all abstract.
    The intention is that by simply declaring elements with these as their
    substitutionGroup, all the right things will happen.
   


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_role>(), B<role>()      - See L<SAN::EAC::ns002::Type::roleType>.

=item B<_title>()      - See L<SAN::EAC::ns002::Type::titleAttrType>.

=item B<_type>(), B<type>()      - See L<SAN::EAC::ns002::Type::typeType>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<arc>()      - See L<SAN::EAC::ns002::Type::arcType>.

=item B<locator>()      - See L<SAN::EAC::ns002::Type::locatorType>.

=item B<resource>()      - See L<SAN::EAC::ns002::Type::resourceType>.

=item B<title>()      - See L<SAN::EAC::ns002::Type::titleEltType>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
