
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:48 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAD::Type::abstract;

use SAN::EAD::Type::stringNotEmpty;

our @ISA=qw(SAN::EAD::Type::stringNotEmpty);

SAN::EAD::Type::abstract->mk_accessors( qw(_langcode));

# Attribute accessor aliases

sub langcode { &_langcode; }

SAN::EAD::Type::abstract->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'langcode' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                   'metaClass' => 'SAN::EAD::Pastor::Meta',
                                                   'name' => 'langcode',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://san.mibac.it/ead-san/',
                                                   'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema'
                                                 }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'langcode'
                         ],
         'base' => 'stringNotEmpty|http://san.mibac.it/ead-san/',
         'baseClasses' => [
                            'SAN::EAD::Type::stringNotEmpty'
                          ],
         'class' => 'SAN::EAD::Type::abstract',
         'contentType' => 'complex',
         'derivedBy' => 'extension',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'isSimpleContent' => 1,
         'metaClass' => 'SAN::EAD::Pastor::Meta',
         'name' => 'abstract',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/ead-san/',
         'xAttributeInfo' => {
                               'langcode' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                    'metaClass' => 'SAN::EAD::Pastor::Meta',
                                                    'name' => 'langcode',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://san.mibac.it/ead-san/',
                                                    'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema'
                                                  }, 'XML::Pastor::Schema::Attribute' )
                             },
         'xAttributes' => [
                            'langcode'
                          ]
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAD::Type::abstract>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<SAN::EAD::Type::stringNotEmpty>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:48 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_langcode>(), B<langcode>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=back


=head1 SEE ALSO

L<SAN::EAD::Type::stringNotEmpty>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
