
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:48 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAD::Type::ead;

use SAN::EAD::Type::archdesc;
use SAN::EAD::archdesc;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAD::Type::ead->mk_accessors( qw(archdesc));

SAN::EAD::Type::ead->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAD::Type::ead',
         'contentType' => 'complex',
         'elementInfo' => {
                            'archdesc' => bless( {
                                                 'class' => 'SAN::EAD::Type::archdesc',
                                                 'definition' => bless( {
                                                                          'baseClasses' => [
                                                                                             'SAN::EAD::Type::archdesc',
                                                                                             'XML::Pastor::Element'
                                                                                           ],
                                                                          'class' => 'SAN::EAD::archdesc',
                                                                          'isRedefinable' => 1,
                                                                          'metaClass' => 'SAN::EAD::Pastor::Meta',
                                                                          'name' => 'archdesc',
                                                                          'scope' => 'global',
                                                                          'targetNamespace' => 'http://san.mibac.it/ead-san/',
                                                                          'type' => 'archdesc|http://san.mibac.it/ead-san/'
                                                                        }, 'XML::Pastor::Schema::Element' ),
                                                 'metaClass' => 'SAN::EAD::Pastor::Meta',
                                                 'name' => 'archdesc',
                                                 'nameIsAutoGenerated' => 1,
                                                 'ref' => 'archdesc|http://san.mibac.it/ead-san/',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://san.mibac.it/ead-san/'
                                               }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'archdesc'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAD::Pastor::Meta',
         'name' => 'ead',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/ead-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAD::Type::ead>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:48 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<archdesc>()      - See L<SAN::EAD::Type::archdesc>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
