
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:48 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAD::Type::physdesc;

use SAN::EAD::Type::stringNotEmpty;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAD::Type::physdesc->mk_accessors( qw(extent));

SAN::EAD::Type::physdesc->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAD::Type::physdesc',
         'contentType' => 'complex',
         'elementInfo' => {
                            'extent' => bless( {
                                               'class' => 'SAN::EAD::Type::stringNotEmpty',
                                               'metaClass' => 'SAN::EAD::Pastor::Meta',
                                               'name' => 'extent',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://san.mibac.it/ead-san/',
                                               'type' => 'stringNotEmpty|http://san.mibac.it/ead-san/'
                                             }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'extent'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAD::Pastor::Meta',
         'name' => 'physdesc',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/ead-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAD::Type::physdesc>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:48 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<extent>()      - See L<SAN::EAD::Type::stringNotEmpty>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
