
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:48 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAD::Type::relatedmaterial;


our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAD::Type::relatedmaterial->mk_accessors( qw(archref));

SAN::EAD::Type::relatedmaterial->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAD::Type::relatedmaterial',
         'contentType' => 'complex',
         'elementInfo' => {
                            'archref' => bless( {
                                                'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                'metaClass' => 'SAN::EAD::Pastor::Meta',
                                                'name' => 'archref',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://san.mibac.it/ead-san/',
                                                'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema'
                                              }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'archref'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAD::Pastor::Meta',
         'name' => 'relatedmaterial',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/ead-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAD::Type::relatedmaterial>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:48 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<archref>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
