
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:47 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::Cat::Type::catListRecords;

use SAN::Cat::Type::catRecord;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::Cat::Type::catListRecords->mk_accessors( qw(catRecord));

SAN::Cat::Type::catListRecords->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::Cat::Type::catListRecords',
         'contentType' => 'complex',
         'elementInfo' => {
                            'catRecord' => bless( {
                                                  'class' => 'SAN::Cat::Type::catRecord',
                                                  'maxOccurs' => 'unbounded',
                                                  'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                  'minOccurs' => '1',
                                                  'name' => 'catRecord',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                  'type' => 'catRecord|http://san.mibac.it/cat-import'
                                                }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'catRecord'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::Cat::Pastor::Meta',
         'name' => 'catListRecords',
         'scope' => 'global',
         'targetNamespace' => 'http://san.mibac.it/cat-import'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::Cat::Type::catListRecords>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:47 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<catRecord>()      - See L<SAN::Cat::Type::catRecord>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
