
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:47 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::Cat::Type::catRecordHeader_type;


our @ISA=qw(XML::Pastor::Builtin::string);

SAN::Cat::Type::catRecordHeader_type->XmlSchemaType( bless( {
         'base' => 'string|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::string'
                          ],
         'class' => 'SAN::Cat::Type::catRecordHeader_type',
         'contentType' => 'simple',
         'derivedBy' => 'restriction',
         'enumeration' => {
                            'complesso archivistico' => 1,
                            'soggetto conservatore' => 1,
                            'soggetto produttore' => 1,
                            'strumento di ricerca' => 1
                          },
         'isRedefinable' => 1,
         'metaClass' => 'SAN::Cat::Pastor::Meta',
         'name' => 'catRecordHeader_type',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/cat-import'
       }, 'XML::Pastor::Schema::SimpleType' ) );

1;


__END__



=head1 NAME

B<SAN::Cat::Type::catRecordHeader_type>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::string>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:47 2015'


=head1 SEE ALSO

L<XML::Pastor::Builtin::string>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
