
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:47 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::Cat::Type::catRecord;

use SAN::Cat::Type::catRecordBody;
use SAN::Cat::Type::catRecordHeader;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::Cat::Type::catRecord->mk_accessors( qw(catRecordHeader catRecordBody));

SAN::Cat::Type::catRecord->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::Cat::Type::catRecord',
         'contentType' => 'complex',
         'elementInfo' => {
                            'catRecordBody' => bless( {
                                                      'class' => 'SAN::Cat::Type::catRecordBody',
                                                      'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                      'minOccurs' => '0',
                                                      'name' => 'catRecordBody',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                      'type' => 'catRecordBody|http://san.mibac.it/cat-import'
                                                    }, 'XML::Pastor::Schema::Element' ),
                            'catRecordHeader' => bless( {
                                                        'class' => 'SAN::Cat::Type::catRecordHeader',
                                                        'maxOccurs' => '1',
                                                        'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                        'minOccurs' => '1',
                                                        'name' => 'catRecordHeader',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                        'type' => 'catRecordHeader|http://san.mibac.it/cat-import'
                                                      }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'catRecordHeader',
                         'catRecordBody'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::Cat::Pastor::Meta',
         'name' => 'catRecord',
         'scope' => 'global',
         'targetNamespace' => 'http://san.mibac.it/cat-import'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::Cat::Type::catRecord>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:47 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<catRecordBody>()      - See L<SAN::Cat::Type::catRecordBody>.

=item B<catRecordHeader>()      - See L<SAN::Cat::Type::catRecordHeader>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
