
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:44:47 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::Cat::Type::catRecordHeader;

use SAN::Cat::Type::catRecordHeader_type;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::Cat::Type::catRecordHeader->mk_accessors( qw(_status _type id lastUpdate));

# Attribute accessor aliases

sub status { &_status; }
sub type { &_type; }

SAN::Cat::Type::catRecordHeader->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'status' => bless( {
                                                 'class' => undef,
                                                 'fixed' => 'deleted',
                                                 'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                 'name' => 'status',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                 'use' => 'optional'
                                               }, 'XML::Pastor::Schema::Attribute' ),
                              'type' => bless( {
                                               'class' => 'SAN::Cat::Type::catRecordHeader_type',
                                               'metaClass' => 'SAN::Cat::Pastor::Meta',
                                               'name' => 'type',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://san.mibac.it/cat-import',
                                               'type' => 'catRecordHeader_type|http://san.mibac.it/cat-import',
                                               'use' => 'required'
                                             }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'status',
                           'type'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::Cat::Type::catRecordHeader',
         'contentType' => 'complex',
         'elementInfo' => {
                            'id' => bless( {
                                           'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                           'metaClass' => 'SAN::Cat::Pastor::Meta',
                                           'name' => 'id',
                                           'scope' => 'local',
                                           'targetNamespace' => 'http://san.mibac.it/cat-import',
                                           'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema'
                                         }, 'XML::Pastor::Schema::Element' ),
                            'lastUpdate' => bless( {
                                                   'class' => 'XML::Pastor::Builtin::dateTime',
                                                   'metaClass' => 'SAN::Cat::Pastor::Meta',
                                                   'name' => 'lastUpdate',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://san.mibac.it/cat-import',
                                                   'type' => 'dateTime|http://www.w3.org/2001/XMLSchema'
                                                 }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'id',
                         'lastUpdate'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::Cat::Pastor::Meta',
         'name' => 'catRecordHeader',
         'scope' => 'global',
         'targetNamespace' => 'http://san.mibac.it/cat-import'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::Cat::Type::catRecordHeader>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:44:47 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_status>(), B<status>()

=item B<_type>(), B<type>()      - See L<SAN::Cat::Type::catRecordHeader_type>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<id>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=item B<lastUpdate>()      - See L<XML::Pastor::Builtin::dateTime>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
