
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::cpfRelation;

use SAN::EAC::Type::cpfRelation_descriptiveNote;
use SAN::EAC::Type::stringNotEmpty;
use SAN::EAC::relationEntry;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::Type::cpfRelation->mk_accessors( qw(_localType relationEntry date descriptiveNote));

# Attribute accessor aliases

sub localType { &_localType; }

SAN::EAC::Type::cpfRelation->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'localType' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::string',
                                                    'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                    'name' => 'localType',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                    'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                  }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'localType'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::Type::cpfRelation',
         'contentType' => 'complex',
         'elementInfo' => {
                            'date' => bless( {
                                             'class' => 'SAN::EAC::Type::stringNotEmpty',
                                             'metaClass' => 'SAN::EAC::Pastor::Meta',
                                             'minOccurs' => '0',
                                             'name' => 'date',
                                             'scope' => 'local',
                                             'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                             'type' => 'stringNotEmpty|http://san.mibac.it/eac-san/'
                                           }, 'XML::Pastor::Schema::Element' ),
                            'descriptiveNote' => bless( {
                                                        'class' => 'SAN::EAC::Type::cpfRelation_descriptiveNote',
                                                        'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                        'minOccurs' => '0',
                                                        'name' => 'descriptiveNote',
                                                        'scope' => 'local',
                                                        'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                        'type' => 'cpfRelation_descriptiveNote|http://san.mibac.it/eac-san/'
                                                      }, 'XML::Pastor::Schema::Element' ),
                            'relationEntry' => bless( {
                                                      'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                      'definition' => bless( {
                                                                               'baseClasses' => [
                                                                                                  'XML::Pastor::Builtin::NMTOKEN',
                                                                                                  'XML::Pastor::Element'
                                                                                                ],
                                                                               'class' => 'SAN::EAC::relationEntry',
                                                                               'isRedefinable' => 1,
                                                                               'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                               'name' => 'relationEntry',
                                                                               'scope' => 'global',
                                                                               'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                               'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema'
                                                                             }, 'XML::Pastor::Schema::Element' ),
                                                      'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                      'name' => 'relationEntry',
                                                      'nameIsAutoGenerated' => 1,
                                                      'ref' => 'relationEntry|http://san.mibac.it/eac-san/',
                                                      'scope' => 'local',
                                                      'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                    }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'relationEntry',
                         'date',
                         'descriptiveNote'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'cpfRelation',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::cpfRelation>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_localType>(), B<localType>()      - See L<XML::Pastor::Builtin::string>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<date>()      - See L<SAN::EAC::Type::stringNotEmpty>.

=item B<descriptiveNote>()      - See L<SAN::EAC::Type::cpfRelation_descriptiveNote>.

=item B<relationEntry>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
