
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::date_standardDate;

use SAN::EAC::Type::date_standardDate_item_0002;
use SAN::EAC::Type::date_standardDate_item_0003;

our @ISA=qw(XML::Pastor::Builtin::Union);

SAN::EAC::Type::date_standardDate->XmlSchemaType( bless( {
         'base' => 'Union|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::Union'
                          ],
         'class' => 'SAN::EAC::Type::date_standardDate',
         'contentType' => 'simple',
         'derivedBy' => 'union',
         'isRedefinable' => 1,
         'memberClasses' => [
                              'SAN::EAC::Type::date_standardDate_item_0002',
                              'SAN::EAC::Type::date_standardDate_item_0003'
                            ],
         'memberTypes' => 'date_standardDate_item_0002 date_standardDate_item_0003',
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'date_standardDate',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::SimpleType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::date_standardDate>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::Union>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 SEE ALSO

L<XML::Pastor::Builtin::Union>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
