
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::description;

use SAN::EAC::Type::biogHist;
use SAN::EAC::Type::descriptiveEntries;
use SAN::EAC::Type::existDates;
use SAN::EAC::Type::placeDates;
use SAN::EAC::biogHist;
use SAN::EAC::descriptiveEntries;
use SAN::EAC::existDates;
use SAN::EAC::placeDates;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::Type::description->mk_accessors( qw(existDates placeDates descriptiveEntries biogHist));

SAN::EAC::Type::description->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::Type::description',
         'contentType' => 'complex',
         'elementInfo' => {
                            'biogHist' => bless( {
                                                 'class' => 'SAN::EAC::Type::biogHist',
                                                 'definition' => bless( {
                                                                          'baseClasses' => [
                                                                                             'SAN::EAC::Type::biogHist',
                                                                                             'XML::Pastor::Element'
                                                                                           ],
                                                                          'class' => 'SAN::EAC::biogHist',
                                                                          'isRedefinable' => 1,
                                                                          'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                          'name' => 'biogHist',
                                                                          'scope' => 'global',
                                                                          'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                          'type' => 'biogHist|http://san.mibac.it/eac-san/'
                                                                        }, 'XML::Pastor::Schema::Element' ),
                                                 'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                 'minOccurs' => '0',
                                                 'name' => 'biogHist',
                                                 'nameIsAutoGenerated' => 1,
                                                 'ref' => 'biogHist|http://san.mibac.it/eac-san/',
                                                 'scope' => 'local',
                                                 'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                               }, 'XML::Pastor::Schema::Element' ),
                            'descriptiveEntries' => bless( {
                                                           'class' => 'SAN::EAC::Type::descriptiveEntries',
                                                           'definition' => bless( {
                                                                                    'baseClasses' => [
                                                                                                       'SAN::EAC::Type::descriptiveEntries',
                                                                                                       'XML::Pastor::Element'
                                                                                                     ],
                                                                                    'class' => 'SAN::EAC::descriptiveEntries',
                                                                                    'isRedefinable' => 1,
                                                                                    'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                    'name' => 'descriptiveEntries',
                                                                                    'scope' => 'global',
                                                                                    'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                                    'type' => 'descriptiveEntries|http://san.mibac.it/eac-san/'
                                                                                  }, 'XML::Pastor::Schema::Element' ),
                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                           'minOccurs' => '0',
                                                           'name' => 'descriptiveEntries',
                                                           'nameIsAutoGenerated' => 1,
                                                           'ref' => 'descriptiveEntries|http://san.mibac.it/eac-san/',
                                                           'scope' => 'local',
                                                           'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                         }, 'XML::Pastor::Schema::Element' ),
                            'existDates' => bless( {
                                                   'class' => 'SAN::EAC::Type::existDates',
                                                   'definition' => bless( {
                                                                            'baseClasses' => [
                                                                                               'SAN::EAC::Type::existDates',
                                                                                               'XML::Pastor::Element'
                                                                                             ],
                                                                            'class' => 'SAN::EAC::existDates',
                                                                            'isRedefinable' => 1,
                                                                            'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                            'name' => 'existDates',
                                                                            'scope' => 'global',
                                                                            'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                            'type' => 'existDates|http://san.mibac.it/eac-san/'
                                                                          }, 'XML::Pastor::Schema::Element' ),
                                                   'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                   'name' => 'existDates',
                                                   'nameIsAutoGenerated' => 1,
                                                   'ref' => 'existDates|http://san.mibac.it/eac-san/',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                 }, 'XML::Pastor::Schema::Element' ),
                            'placeDates' => bless( {
                                                   'class' => 'SAN::EAC::Type::placeDates',
                                                   'definition' => bless( {
                                                                            'baseClasses' => [
                                                                                               'SAN::EAC::Type::placeDates',
                                                                                               'XML::Pastor::Element'
                                                                                             ],
                                                                            'class' => 'SAN::EAC::placeDates',
                                                                            'isRedefinable' => 1,
                                                                            'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                            'name' => 'placeDates',
                                                                            'scope' => 'global',
                                                                            'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                            'type' => 'placeDates|http://san.mibac.it/eac-san/'
                                                                          }, 'XML::Pastor::Schema::Element' ),
                                                   'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                   'minOccurs' => '0',
                                                   'name' => 'placeDates',
                                                   'nameIsAutoGenerated' => 1,
                                                   'ref' => 'placeDates|http://san.mibac.it/eac-san/',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                 }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'existDates',
                         'placeDates',
                         'descriptiveEntries',
                         'biogHist'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'description',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::description>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<biogHist>()      - See L<SAN::EAC::Type::biogHist>.

=item B<descriptiveEntries>()      - See L<SAN::EAC::Type::descriptiveEntries>.

=item B<existDates>()      - See L<SAN::EAC::Type::existDates>.

=item B<placeDates>()      - See L<SAN::EAC::Type::placeDates>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
