
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::eac;

use SAN::EAC::Type::control;
use SAN::EAC::Type::cpfDescription;
use SAN::EAC::control;
use SAN::EAC::cpfDescription;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::Type::eac->mk_accessors( qw(control cpfDescription));

SAN::EAC::Type::eac->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::Type::eac',
         'contentType' => 'complex',
         'elementInfo' => {
                            'control' => bless( {
                                                'class' => 'SAN::EAC::Type::control',
                                                'definition' => bless( {
                                                                         'baseClasses' => [
                                                                                            'SAN::EAC::Type::control',
                                                                                            'XML::Pastor::Element'
                                                                                          ],
                                                                         'class' => 'SAN::EAC::control',
                                                                         'isRedefinable' => 1,
                                                                         'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                         'name' => 'control',
                                                                         'scope' => 'global',
                                                                         'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                         'type' => 'control|http://san.mibac.it/eac-san/'
                                                                       }, 'XML::Pastor::Schema::Element' ),
                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                'name' => 'control',
                                                'nameIsAutoGenerated' => 1,
                                                'ref' => 'control|http://san.mibac.it/eac-san/',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                              }, 'XML::Pastor::Schema::Element' ),
                            'cpfDescription' => bless( {
                                                       'class' => 'SAN::EAC::Type::cpfDescription',
                                                       'definition' => bless( {
                                                                                'baseClasses' => [
                                                                                                   'SAN::EAC::Type::cpfDescription',
                                                                                                   'XML::Pastor::Element'
                                                                                                 ],
                                                                                'class' => 'SAN::EAC::cpfDescription',
                                                                                'isRedefinable' => 1,
                                                                                'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                'name' => 'cpfDescription',
                                                                                'scope' => 'global',
                                                                                'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                                'type' => 'cpfDescription|http://san.mibac.it/eac-san/'
                                                                              }, 'XML::Pastor::Schema::Element' ),
                                                       'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                       'name' => 'cpfDescription',
                                                       'nameIsAutoGenerated' => 1,
                                                       'ref' => 'cpfDescription|http://san.mibac.it/eac-san/',
                                                       'scope' => 'local',
                                                       'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                     }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'control',
                         'cpfDescription'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'eac',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::eac>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<control>()      - See L<SAN::EAC::Type::control>.

=item B<cpfDescription>()      - See L<SAN::EAC::Type::cpfDescription>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
