
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::identity;

use SAN::EAC::Type::entityType;
use SAN::EAC::Type::identity_localType;
use SAN::EAC::Type::nameEntry;
use SAN::EAC::Type::nameEntryParallel;
use SAN::EAC::entityType;
use SAN::EAC::nameEntry;
use SAN::EAC::nameEntryParallel;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::Type::identity->mk_accessors( qw(_localType entityType nameEntry nameEntryParallel));

# Attribute accessor aliases

sub localType { &_localType; }

SAN::EAC::Type::identity->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'localType' => bless( {
                                                    'class' => 'SAN::EAC::Type::identity_localType',
                                                    'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                    'name' => 'localType',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                    'type' => 'identity_localType|http://san.mibac.it/eac-san/'
                                                  }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'localType'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::Type::identity',
         'contentType' => 'complex',
         'elementInfo' => {
                            'entityType' => bless( {
                                                   'class' => 'SAN::EAC::Type::entityType',
                                                   'definition' => bless( {
                                                                            'baseClasses' => [
                                                                                               'SAN::EAC::Type::entityType',
                                                                                               'XML::Pastor::Element'
                                                                                             ],
                                                                            'class' => 'SAN::EAC::entityType',
                                                                            'isRedefinable' => 1,
                                                                            'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                            'name' => 'entityType',
                                                                            'scope' => 'global',
                                                                            'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                            'type' => 'entityType|http://san.mibac.it/eac-san/'
                                                                          }, 'XML::Pastor::Schema::Element' ),
                                                   'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                   'minOccurs' => '0',
                                                   'name' => 'entityType',
                                                   'nameIsAutoGenerated' => 1,
                                                   'ref' => 'entityType|http://san.mibac.it/eac-san/',
                                                   'scope' => 'local',
                                                   'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                 }, 'XML::Pastor::Schema::Element' ),
                            'nameEntry' => bless( {
                                                  'class' => 'SAN::EAC::Type::nameEntry',
                                                  'definition' => bless( {
                                                                           'baseClasses' => [
                                                                                              'SAN::EAC::Type::nameEntry',
                                                                                              'XML::Pastor::Element'
                                                                                            ],
                                                                           'class' => 'SAN::EAC::nameEntry',
                                                                           'isRedefinable' => 1,
                                                                           'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                           'name' => 'nameEntry',
                                                                           'scope' => 'global',
                                                                           'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                           'type' => 'nameEntry|http://san.mibac.it/eac-san/'
                                                                         }, 'XML::Pastor::Schema::Element' ),
                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                  'name' => 'nameEntry',
                                                  'nameIsAutoGenerated' => 1,
                                                  'ref' => 'nameEntry|http://san.mibac.it/eac-san/',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                }, 'XML::Pastor::Schema::Element' ),
                            'nameEntryParallel' => bless( {
                                                          'class' => 'SAN::EAC::Type::nameEntryParallel',
                                                          'definition' => bless( {
                                                                                   'baseClasses' => [
                                                                                                      'SAN::EAC::Type::nameEntryParallel',
                                                                                                      'XML::Pastor::Element'
                                                                                                    ],
                                                                                   'class' => 'SAN::EAC::nameEntryParallel',
                                                                                   'isRedefinable' => 1,
                                                                                   'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                   'name' => 'nameEntryParallel',
                                                                                   'scope' => 'global',
                                                                                   'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                                   'type' => 'nameEntryParallel|http://san.mibac.it/eac-san/'
                                                                                 }, 'XML::Pastor::Schema::Element' ),
                                                          'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                          'name' => 'nameEntryParallel',
                                                          'nameIsAutoGenerated' => 1,
                                                          'ref' => 'nameEntryParallel|http://san.mibac.it/eac-san/',
                                                          'scope' => 'local',
                                                          'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                        }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'entityType',
                         'nameEntry',
                         'nameEntryParallel'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'identity',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::identity>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_localType>(), B<localType>()      - See L<SAN::EAC::Type::identity_localType>.

=back


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<entityType>()      - See L<SAN::EAC::Type::entityType>.

=item B<nameEntry>()      - See L<SAN::EAC::Type::nameEntry>.

=item B<nameEntryParallel>()      - See L<SAN::EAC::Type::nameEntryParallel>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
