
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::nameEntryParallel;

use SAN::EAC::Type::nameEntryParallel_nameEntry;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::Type::nameEntryParallel->mk_accessors( qw(nameEntry));

SAN::EAC::Type::nameEntryParallel->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::Type::nameEntryParallel',
         'contentType' => 'complex',
         'elementInfo' => {
                            'nameEntry' => bless( {
                                                  'class' => 'SAN::EAC::Type::nameEntryParallel_nameEntry',
                                                  'maxOccurs' => 'unbounded',
                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                  'minOccurs' => '2',
                                                  'name' => 'nameEntry',
                                                  'scope' => 'local',
                                                  'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                  'type' => 'nameEntryParallel_nameEntry|http://san.mibac.it/eac-san/'
                                                }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'nameEntry'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'nameEntryParallel',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::nameEntryParallel>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<nameEntry>()      - See L<SAN::EAC::Type::nameEntryParallel_nameEntry>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
