
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::otherRecordId;


our @ISA=qw(XML::Pastor::Builtin::NMTOKEN);

SAN::EAC::Type::otherRecordId->mk_accessors( qw(_localType));

# Attribute accessor aliases

sub localType { &_localType; }

SAN::EAC::Type::otherRecordId->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'localType' => bless( {
                                                    'class' => 'XML::Pastor::Builtin::NMTOKEN',
                                                    'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                    'name' => 'localType',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                    'type' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema',
                                                    'use' => 'required'
                                                  }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'localType'
                         ],
         'base' => 'NMTOKEN|http://www.w3.org/2001/XMLSchema',
         'baseClasses' => [
                            'XML::Pastor::Builtin::NMTOKEN'
                          ],
         'class' => 'SAN::EAC::Type::otherRecordId',
         'contentType' => 'complex',
         'derivedBy' => 'extension',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'isSimpleContent' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'otherRecordId',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::otherRecordId>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::Builtin::NMTOKEN>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_localType>(), B<localType>()      - See L<XML::Pastor::Builtin::NMTOKEN>.

=back


=head1 SEE ALSO

L<XML::Pastor::Builtin::NMTOKEN>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
