
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::Type::relations;

use SAN::EAC::Type::cpfRelation;
use SAN::EAC::Type::resourceRelation;
use SAN::EAC::cpfRelation;
use SAN::EAC::resourceRelation;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::EAC::Type::relations->mk_accessors( qw(resourceRelation cpfRelation));

SAN::EAC::Type::relations->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::EAC::Type::relations',
         'contentType' => 'complex',
         'elementInfo' => {
                            'cpfRelation' => bless( {
                                                    'class' => 'SAN::EAC::Type::cpfRelation',
                                                    'definition' => bless( {
                                                                             'baseClasses' => [
                                                                                                'SAN::EAC::Type::cpfRelation',
                                                                                                'XML::Pastor::Element'
                                                                                              ],
                                                                             'class' => 'SAN::EAC::cpfRelation',
                                                                             'isRedefinable' => 1,
                                                                             'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                             'name' => 'cpfRelation',
                                                                             'scope' => 'global',
                                                                             'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                             'type' => 'cpfRelation|http://san.mibac.it/eac-san/'
                                                                           }, 'XML::Pastor::Schema::Element' ),
                                                    'maxOccurs' => 'unbounded',
                                                    'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                    'minOccurs' => '0',
                                                    'name' => 'cpfRelation',
                                                    'nameIsAutoGenerated' => 1,
                                                    'ref' => 'cpfRelation|http://san.mibac.it/eac-san/',
                                                    'scope' => 'local',
                                                    'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                  }, 'XML::Pastor::Schema::Element' ),
                            'resourceRelation' => bless( {
                                                         'class' => 'SAN::EAC::Type::resourceRelation',
                                                         'definition' => bless( {
                                                                                  'baseClasses' => [
                                                                                                     'SAN::EAC::Type::resourceRelation',
                                                                                                     'XML::Pastor::Element'
                                                                                                   ],
                                                                                  'class' => 'SAN::EAC::resourceRelation',
                                                                                  'isRedefinable' => 1,
                                                                                  'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                                                  'name' => 'resourceRelation',
                                                                                  'scope' => 'global',
                                                                                  'targetNamespace' => 'http://san.mibac.it/eac-san/',
                                                                                  'type' => 'resourceRelation|http://san.mibac.it/eac-san/'
                                                                                }, 'XML::Pastor::Schema::Element' ),
                                                         'maxOccurs' => 'unbounded',
                                                         'metaClass' => 'SAN::EAC::Pastor::Meta',
                                                         'minOccurs' => '0',
                                                         'name' => 'resourceRelation',
                                                         'nameIsAutoGenerated' => 1,
                                                         'ref' => 'resourceRelation|http://san.mibac.it/eac-san/',
                                                         'scope' => 'local',
                                                         'targetNamespace' => 'http://san.mibac.it/eac-san/'
                                                       }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'resourceRelation',
                         'cpfRelation'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'relations',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/eac-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::Type::relations>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<cpfRelation>()      - See L<SAN::EAC::Type::cpfRelation>.

=item B<resourceRelation>()      - See L<SAN::EAC::Type::resourceRelation>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
