
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:08 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::Ricerca::Type::archdesc;

use SAN::Ricerca::Type::did;
use SAN::Ricerca::did;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::Ricerca::Type::archdesc->mk_accessors( qw(did));

SAN::Ricerca::Type::archdesc->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::Ricerca::Type::archdesc',
         'contentType' => 'complex',
         'elementInfo' => {
                            'did' => bless( {
                                            'class' => 'SAN::Ricerca::Type::did',
                                            'definition' => bless( {
                                                                     'baseClasses' => [
                                                                                        'SAN::Ricerca::Type::did',
                                                                                        'XML::Pastor::Element'
                                                                                      ],
                                                                     'class' => 'SAN::Ricerca::did',
                                                                     'isRedefinable' => 1,
                                                                     'metaClass' => 'SAN::Ricerca::Pastor::Meta',
                                                                     'name' => 'did',
                                                                     'scope' => 'global',
                                                                     'targetNamespace' => 'http://san.mibac.it/ricerca-san/',
                                                                     'type' => 'did|http://san.mibac.it/ricerca-san/'
                                                                   }, 'XML::Pastor::Schema::Element' ),
                                            'metaClass' => 'SAN::Ricerca::Pastor::Meta',
                                            'name' => 'did',
                                            'nameIsAutoGenerated' => 1,
                                            'ref' => 'did|http://san.mibac.it/ricerca-san/',
                                            'scope' => 'local',
                                            'targetNamespace' => 'http://san.mibac.it/ricerca-san/'
                                          }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'did'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::Ricerca::Pastor::Meta',
         'name' => 'archdesc',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/ricerca-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::Ricerca::Type::archdesc>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:08 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<did>()      - See L<SAN::Ricerca::Type::did>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
