
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:08 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::Ricerca::Type::edition;

use SAN::Ricerca::Type::extptr;
use SAN::Ricerca::extptr;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::Ricerca::Type::edition->mk_accessors( qw(extptr));

SAN::Ricerca::Type::edition->XmlSchemaType( bless( {
         'attributeInfo' => {},
         'attributePrefix' => '_',
         'attributes' => [],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::Ricerca::Type::edition',
         'contentType' => 'complex',
         'elementInfo' => {
                            'extptr' => bless( {
                                               'class' => 'SAN::Ricerca::Type::extptr',
                                               'definition' => bless( {
                                                                        'baseClasses' => [
                                                                                           'SAN::Ricerca::Type::extptr',
                                                                                           'XML::Pastor::Element'
                                                                                         ],
                                                                        'class' => 'SAN::Ricerca::extptr',
                                                                        'isRedefinable' => 1,
                                                                        'metaClass' => 'SAN::Ricerca::Pastor::Meta',
                                                                        'name' => 'extptr',
                                                                        'scope' => 'global',
                                                                        'targetNamespace' => 'http://san.mibac.it/ricerca-san/',
                                                                        'type' => 'extptr|http://san.mibac.it/ricerca-san/'
                                                                      }, 'XML::Pastor::Schema::Element' ),
                                               'metaClass' => 'SAN::Ricerca::Pastor::Meta',
                                               'name' => 'extptr',
                                               'nameIsAutoGenerated' => 1,
                                               'ref' => 'extptr|http://san.mibac.it/ricerca-san/',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://san.mibac.it/ricerca-san/'
                                             }, 'XML::Pastor::Schema::Element' )
                          },
         'elements' => [
                         'extptr'
                       ],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::Ricerca::Pastor::Meta',
         'name' => 'edition',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/ricerca-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::Ricerca::Type::edition>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:08 2015'


=head1 CHILD ELEMENT ACCESSORS

=over

=item B<extptr>()      - See L<SAN::Ricerca::Type::extptr>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
