
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:08 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::Ricerca::Type::extptr;

use SAN::Ricerca::Type::stringNotEmpty;

our @ISA=qw(XML::Pastor::ComplexType);

SAN::Ricerca::Type::extptr->mk_accessors( qw(_href _title));

# Attribute accessor aliases

sub href { &_href; }
sub title { &_title; }

SAN::Ricerca::Type::extptr->XmlSchemaType( bless( {
         'attributeInfo' => {
                              'href' => bless( {
                                               'class' => 'XML::Pastor::Builtin::anyURI',
                                               'metaClass' => 'SAN::Ricerca::Pastor::Meta',
                                               'name' => 'href',
                                               'scope' => 'local',
                                               'targetNamespace' => 'http://san.mibac.it/ricerca-san/',
                                               'type' => 'anyURI|http://www.w3.org/2001/XMLSchema',
                                               'use' => 'required'
                                             }, 'XML::Pastor::Schema::Attribute' ),
                              'title' => bless( {
                                                'class' => 'SAN::Ricerca::Type::stringNotEmpty',
                                                'metaClass' => 'SAN::Ricerca::Pastor::Meta',
                                                'name' => 'title',
                                                'scope' => 'local',
                                                'targetNamespace' => 'http://san.mibac.it/ricerca-san/',
                                                'type' => 'stringNotEmpty|http://san.mibac.it/ricerca-san/'
                                              }, 'XML::Pastor::Schema::Attribute' )
                            },
         'attributePrefix' => '_',
         'attributes' => [
                           'href',
                           'title'
                         ],
         'baseClasses' => [
                            'XML::Pastor::ComplexType'
                          ],
         'class' => 'SAN::Ricerca::Type::extptr',
         'contentType' => 'complex',
         'elementInfo' => {},
         'elements' => [],
         'isRedefinable' => 1,
         'metaClass' => 'SAN::Ricerca::Pastor::Meta',
         'name' => 'extptr',
         'nameIsAutoGenerated' => 1,
         'scope' => 'local',
         'targetNamespace' => 'http://san.mibac.it/ricerca-san/'
       }, 'XML::Pastor::Schema::ComplexType' ) );

1;


__END__



=head1 NAME

B<SAN::Ricerca::Type::extptr>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<XML::Pastor::ComplexType>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:08 2015'


=head1 ATTRIBUTE ACCESSORS

=over

=item B<_href>(), B<href>()      - See L<XML::Pastor::Builtin::anyURI>.

=item B<_title>(), B<title>()      - See L<SAN::Ricerca::Type::stringNotEmpty>.

=back


=head1 SEE ALSO

L<XML::Pastor::ComplexType>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
