
#PASTOR: Code generated by XML::Pastor/1.0.4 at 'Sun Jun 28 20:45:06 2015'

use utf8;
use strict;
use warnings;
no warnings qw(uninitialized);

use XML::Pastor;



#================================================================

package SAN::EAC::ns002::title;

use SAN::EAC::ns002::Type::titleEltType;

our @ISA=qw(SAN::EAC::ns002::Type::titleEltType XML::Pastor::Element);

SAN::EAC::ns002::title->XmlSchemaElement( bless( {
         'abstract' => 'true',
         'baseClasses' => [
                            'SAN::EAC::ns002::Type::titleEltType',
                            'XML::Pastor::Element'
                          ],
         'class' => 'SAN::EAC::ns002::title',
         'isRedefinable' => 1,
         'metaClass' => 'SAN::EAC::Pastor::Meta',
         'name' => 'title',
         'scope' => 'global',
         'targetNamespace' => 'http://www.w3.org/1999/xlink',
         'type' => 'titleEltType|http://www.w3.org/1999/xlink'
       }, 'XML::Pastor::Schema::Element' ) );

1;


__END__



=head1 NAME

B<SAN::EAC::ns002::title>  -  A class generated by L<XML::Pastor> . 


=head1 ISA

This class descends from L<SAN::EAC::ns002::Type::titleEltType>, L<XML::Pastor::Element>.


=head1 CODE GENERATION

This module was automatically generated by L<XML::Pastor> version 1.0.4 at 'Sun Jun 28 20:45:06 2015'


=head1 SEE ALSO

L<SAN::EAC::ns002::Type::titleEltType>, L<XML::Pastor::Element>, L<XML::Pastor>, L<XML::Pastor::Type>, L<XML::Pastor::ComplexType>, L<XML::Pastor::SimpleType>


=cut
